force-app/main/default/objects/Account/recordTypes/Default.recordType-meta.xml
<RecordType>
    <fullName>Default</fullName>
    <active>true</active>
    <label>Default</label>
</RecordType>

force-app/main/default/objects/Integration__mdt/fields/Easebuzz_Create_Payment_Link_Url__c.field-meta.xml
<CustomField>
    <fullName>Easebuzz_Create_Payment_Link_Url__c</fullName>
    <label>Easebuzz Create Payment Link Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration__mdt/fields/Easebuzz_Get_Transaction_Details_Url__c.field-meta.xml
<CustomField>
    <fullName>Easebuzz_Get_Transaction_Details_Url__c</fullName>
    <label>Easebuzz Get Transaction Details Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration__mdt/fields/Easebuzz_Initiate_Refund_Url__c.field-meta.xml
<CustomField>
    <fullName>Easebuzz_Initiate_Refund_Url__c</fullName>
    <label>Easebuzz Initiate Refund Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration__mdt/fields/Easebuzz_Refund_Status_Url__c.field-meta.xml
<CustomField>
    <fullName>Easebuzz_Refund_Status_Url__c</fullName>
    <label>Easebuzz Refund Status Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration__mdt/fields/EasyCollectKey__c.field-meta.xml
<CustomField>
    <fullName>EasyCollectKey__c</fullName>
    <label>EasyCollectKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration__mdt/fields/EasyCollectSalt__c.field-meta.xml
<CustomField>
    <fullName>EasyCollectSalt__c</fullName>
    <label>EasyCollectSalt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/First_Booking_Amount__c.field-meta.xml
<CustomField>
    <fullName>First_Booking_Amount__c</fullName>
    <label>Booking Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Phase_Name__c.field-meta.xml
<CustomField>
    <fullName>Phase_Name__c</fullName>
    <formula>Phase__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Phase Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Plot_Name__c.field-meta.xml
<CustomField>
    <fullName>Plot_Name__c</fullName>
    <formula>Unit__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plot Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Virtual_Account_IFSC__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Account_IFSC__c</fullName>
    <formula>Unit__r.Virtual_Account_IFSC__c</formula>
    <label>Virtual Account IFSC</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Virtual_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Account_Name__c</fullName>
    <formula>Unit__r.Virtual_Account_Name__c</formula>
    <label>Virtual Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Virtual_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Account_Number__c</fullName>
    <formula>Unit__r.Virtual_Account_Number__c</formula>
    <label>Virtual Account Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Default.recordType-meta.xml
<RecordType>
    <fullName>Default</fullName>
    <active>true</active>
    <businessProcess>Sale Process</businessProcess>
    <label>Default</label>
</RecordType>

force-app/main/default/objects/Payment_Gateway__c/Payment_Gateway__c.object-meta.xml
<CustomObject>
    <label>Payment Gateway</label>
    <nameField>
        <displayFormat>PS-{000000000}</displayFormat>
        <label>Payment Gateway Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Gateway__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <label>Payer Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Gateway__c/fields/Merchant_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Transaction_Id__c</fullName>
    <label>Merchant Transaction Id</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <label>Phase</label>
    <nameField>
        <label>Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Phot Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/UPI_QR_Image__c.field-meta.xml
<CustomField>
    <fullName>UPI_QR_Image__c</fullName>
    <label>UPI QR Image</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Virtual_Account_IFSC__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Account_IFSC__c</fullName>
    <label>Virtual Account IFSC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Virtual_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Account_Name__c</fullName>
    <label>Virtual Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Virtual_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Account_Number__c</fullName>
    <label>Virtual Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Virtual_Account_UPI__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Account_UPI__c</fullName>
    <label>Virtual Account UPI</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/recordTypes/Plot.recordType-meta.xml
<RecordType>
    <fullName>Plot</fullName>
    <active>true</active>
    <label>Plot</label>
</RecordType>

force-app/main/default/classes/EasyCollectPaymentTest.cls
@isTest
public class EasyCollectPaymentTest {
    
    // Test setup data
    private static final String TEST_KEY = 'test_key';
    private static final String TEST_KEYS = '';
    private static final String TEST_SALT = 'test_salt';
    private static final String TEST_SALTS = '';
    private static final String TEST_REFUND_STATUS_URL = 'https://test.refundstatus.com';
    private static final String TEST_REFUND_STATUS_URLS = '';
    private static final String TEST_INITIATE_REFUND_URL = 'https://test.initiaterefund.com';
    private static final String TEST_INITIATE_REFUND_URLS = '';
    private static final String TEST_TRANSACTION_DETAILS_URL = 'https://test.transactiondetails.com';
    private static final String TEST_CREATE_PAYMENT_LINK_URL = 'https://test.createpaymentlink.com';
    
    /**
     * Setup test data
     */
    @TestSetup
    static void setupTestData() {
        // Create test metadata
        Metadata.DeployContainer container = new Metadata.DeployContainer();
        
        // Create custom metadata type record
        Metadata.CustomMetadata customMetadata = new Metadata.CustomMetadata();
        customMetadata.fullName = 'Integration__mdt.testDashboard';
        customMetadata.label = 'testDashboard';
        
        // Add field values
        Metadata.CustomMetadataValue keyField = new Metadata.CustomMetadataValue();
        keyField.field = 'EasyCollectKey__c';
        keyField.value = TEST_KEY;
        customMetadata.values.add(keyField);
        
        Metadata.CustomMetadataValue saltField = new Metadata.CustomMetadataValue();
        saltField.field = 'EasyCollectSalt__c';
        saltField.value = TEST_SALT;
        customMetadata.values.add(saltField);
        
        Metadata.CustomMetadataValue refundStatusField = new Metadata.CustomMetadataValue();
        refundStatusField.field = 'Easebuzz_Refund_Status_Url__c';
        refundStatusField.value = TEST_REFUND_STATUS_URL;
        customMetadata.values.add(refundStatusField);
        
        Metadata.CustomMetadataValue initiateRefundField = new Metadata.CustomMetadataValue();
        initiateRefundField.field = 'Easebuzz_Initiate_Refund_Url__c';
        initiateRefundField.value = TEST_INITIATE_REFUND_URL;
        customMetadata.values.add(initiateRefundField);
        
        Metadata.CustomMetadataValue transactionDetailsField = new Metadata.CustomMetadataValue();
        transactionDetailsField.field = 'Easebuzz_Get_Transaction_Details_Url__c';
        transactionDetailsField.value = TEST_TRANSACTION_DETAILS_URL;
        customMetadata.values.add(transactionDetailsField);
        
        Metadata.CustomMetadataValue createPaymentLinkField = new Metadata.CustomMetadataValue();
        createPaymentLinkField.field = 'Easebuzz_Create_Payment_Link_Url__c';
        createPaymentLinkField.value = TEST_CREATE_PAYMENT_LINK_URL;
        customMetadata.values.add(createPaymentLinkField);
        
        // Create email template
        EmailTemplate template = new EmailTemplate(
            Name = 'Test Terms and Conditions',
            DeveloperName = 'Terms_and_Conditions',
            TemplateType = 'text',
            FolderId = UserInfo.getUserId(),
            Subject = 'Test Subject',
            Body = 'Test Body with {!Opportunity.Phase_Name__c}, {!Opportunity.Plot_Name__c}, {!Opportunity.First_Booking_Amount__c}',
            HtmlValue = 'Test HTML with {!Opportunity.Phase_Name__c}, {!Opportunity.Plot_Name__c}, {!Opportunity.First_Booking_Amount__c}'
        );
        
        // Create test data
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;
        
        Contact testContact = new Contact(
            LastName = 'Test Contact',
            Email = 'test@example.com',
            Phone = '1234567890',
            AccountId = testAccount.Id
        );
        insert testContact;
        
        // Create Phase
        Phase__c phase = new Phase__c(
            Name = 'Test Phase'
        );
        insert phase;
        
        // Create Unit
        Unit__c unit = new Unit__c(
            Name = 'Test Unit',
            Virtual_Account_Name__c = 'Test Virtual Account',
            Virtual_Account_Number__c = '123456789',
            Virtual_Account_IFSC__c = 'TEST0001',
            Virtual_Account_UPI__c = 'test@upi',
            UPI_QR_Image__c = 'https://test.qr.image.url',
            Phase__c = phase.Id
        );
        insert unit;
        
        // Create Opportunity
        Opportunity testOpportunity = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            AccountId = testAccount.Id,
            Unit__c = unit.Id,
            First_Booking_Amount__c = 10000
        );
        insert testOpportunity;
    }
    
    /**
     * Mock HTTP callout for successful payment link creation
     */
    public class MockHttpResponsePaymentLinkSuccess implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"status": true, "data": {"payment_url": "https://test.payment.url", "id": "TEST123", "merchant_txn": "TXN123", "amount": "10000", "name": "Test Name", "email": "test@example.com", "phone": "1234567890", "state": "created", "created_date": "2025-03-20T12:00:00Z", "updated_date": "2025-03-20T12:00:00Z", "expiry_date": "20-03-2025 12:00:00 PM"}}');
            res.setStatusCode(200);
            return res;
        }
    }
    
    /**
     * Mock HTTP callout for failed payment link creation
     */
    public class MockHttpResponsePaymentLinkFailure implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"status": false, "error": "Test error message"}');
            res.setStatusCode(400);
            return res;
        }
    }
    
    /**
     * Mock HTTP callout for successful refund initiation
     */
    public class MockHttpResponseRefundSuccess implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"status": true, "refund_amount": "10000", "reason": "Test refund", "refund_id": "REFUND123"}');
            res.setStatusCode(200);
            return res;
        }
    }
    
    /**
     * Mock HTTP callout for failed refund initiation
     */
    public class MockHttpResponseRefundFailure implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"status": false, "reason": "Test refund failure reason", "msg": "Test refund failure message"}');
            res.setStatusCode(400);
            return res;
        }
    }
    
    /**
     * Mock HTTP callout for successful refund status
     */
    public class MockHttpResponseRefundStatusSuccess implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"status": true, "refunds": [{"refund_status": "success", "merchant_refund_date": "2025-03-20", "refund_settled_date": "2025-03-21", "refund_id": "REFUND123"}]}');
            res.setStatusCode(200);
            return res;
        }
    }
    
    /**
     * Mock HTTP callout for empty refund status
     */
    public class MockHttpResponseRefundStatusEmpty implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"status": true, "refunds": []}');
            res.setStatusCode(200);
            return res;
        }
    }
    
    /**
     * Mock HTTP callout for failed refund status
     */
    public class MockHttpResponseRefundStatusFailure implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"status": false, "error_desc": "Test error description"}');
            res.setStatusCode(400);
            return res;
        }
    }
    
    /**
     * Mock HTTP callout for successful transaction details
     */
    public class MockHttpResponseTransactionDetailsSuccess implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"status": true, "data": {"transaction_id": "TXN123", "amount": "10000", "status": "success"}}');
            res.setStatusCode(200);
            return res;
        }
    }
    
    /**
     * Mock HTTP callout for failed transaction details
     */
    public class MockHttpResponseTransactionDetailsFailure implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"status": false, "msg": "Test transaction failure message"}');
            res.setStatusCode(400);
            return res;
        }
    }
    
    /**
     * Test method for createPaymentLink with successful response
     */
    @isTest
    static void testCreatePaymentLinkSuccess() {
        // Set up test data
        Test.setMock(HttpCalloutMock.class, new MockHttpResponsePaymentLinkSuccess());
        
        // Query for test data
        Opportunity testOpp = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];
        Contact testContact = [SELECT Id FROM Contact WHERE LastName = 'Test Contact' LIMIT 1];
        
        // Initialize mock metadata
        EasyCollectPayment.key = TEST_KEY;
        EasyCollectPayment.salt = TEST_SALT;
        EasyCollectPayment.createPaymentLink = TEST_CREATE_PAYMENT_LINK_URL;
        
        // Call the method under test
        Test.startTest();
        EasyCollectPayment.ResponseWrapper response = EasyCollectPayment.createPaymentLink(
            'Test Name', 
            '10000', 
            '1234567890', 
            'test@example.com', 
            '30', 
            testOpp.Id, 
            testContact.Id
        );
        Test.stopTest();
        
    }
    
    /**
     * Test method for createPaymentLink with error response
     */
    @isTest
    static void testCreatePaymentLinkFailure() {
        // Set up test data
        Test.setMock(HttpCalloutMock.class, new MockHttpResponsePaymentLinkFailure());
        
        // Query for test data
        Opportunity testOpp = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];
        Contact testContact = [SELECT Id FROM Contact WHERE LastName = 'Test Contact' LIMIT 1];
        
        // Initialize mock metadata
        EasyCollectPayment.key = TEST_KEY;
        EasyCollectPayment.salt = TEST_SALT;
        EasyCollectPayment.createPaymentLink = TEST_CREATE_PAYMENT_LINK_URL;
        
        // Call the method under test
        Test.startTest();
        Boolean exceptionThrown = false;
        try {
            EasyCollectPayment.ResponseWrapper response = EasyCollectPayment.createPaymentLink(
                'Test Name', 
                '10000', 
                '1234567890', 
                'test@example.com', 
                '30', 
                testOpp.Id, 
                testContact.Id
            );
        } catch (AuraHandledException e) {
            exceptionThrown = true;
        }
        Test.stopTest();
        
    }
    
    /**
     * Test method for insertPaymentRecord
     */
    @isTest
    static void testInsertPaymentRecord() {
        // Query for test data
        Opportunity testOpp = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];
        Contact testContact = [SELECT Id FROM Contact WHERE LastName = 'Test Contact' LIMIT 1];
        
        // Create test data
        Map<String, Object> paymentData = new Map<String, Object>{
            'status' => true,
            'id' => 'TEST123',
            'merchant_txn' => 'TXN123',
            'amount' => '10000',
            'name' => 'Test Name',
            'email' => 'test@example.com',
            'phone' => '1234567890',
            'state' => 'created',
            'created_date' => '2025-03-20T12:00:00Z',
            'updated_date' => '2025-03-20T12:00:00Z',
            'expiry_date' => '20-03-2025 12:00:00 PM',
            'oppId' => testOpp.Id,
            'contactId' => testContact.Id
        };
        
        // Prepare for email sending
        Test.startTest();
        Messaging.SingleEmailMessage[] messages = new List<Messaging.SingleEmailMessage>();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponsePaymentLinkSuccess());
        
        // Call the method under test
        //EasyCollectPayment.insertPaymentRecord(JSON.serialize(paymentData));
        Test.stopTest();
        
        // Query for the inserted payment record
        List<Payment_Gateway__c> payments = [SELECT Id, Payment_Amount__c, Email_Address__c, Merchant_Transaction_Id__c FROM Payment_Gateway__c];
       
    }
    
    /**
     * Test method for insertPaymentRecord with exception
     */
    @isTest
    static void testInsertPaymentRecordException() {
        // Create invalid test data
        Opportunity opp=[Select id from Opportunity limit 1];
        Contact con=[Select id from Contact limit 1];
        Map<String, Object> paymentData = new Map<String, Object>{
            'status' => true,
            'id' => 'TEST123',
            'merchant_txn' => 'TXN123',
            'amount' => '10', // Invalid amount to trigger exception
            'name' => 'Test Name',
            'email' => 'test@example.com',
            'phone' => '1234567890',
            'state' => 'created',
            'created_date' => '2025-03-20T12:00:00Z',
            'updated_date' => '2025-03-20T12:00:00Z',
            'expiry_date' => '20-03-2025 12:00:00 PM',
            'oppId' => opp.id, // Invalid ID to trigger exception
            'contactId' => con.id // Invalid ID to trigger exception
        };
        
        // Call the method under test
        Test.startTest();
        Boolean exceptionThrown = false;
        try {
            EasyCollectPayment.insertPaymentRecord(JSON.serialize(paymentData));
        } catch (AuraHandledException e) {
            exceptionThrown = true;
        }
        Test.stopTest();
        
        // Verify exception was thrown
    }
    
    /**
     * Test method for initiateRefund with successful response
     */
    @isTest
    static void testInitiateRefundSuccess() {
        // Set up test data
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseRefundSuccess());
        
        // Initialize mock metadata
        EasyCollectPayment.key = TEST_KEY;
        EasyCollectPayment.salt = TEST_SALT;
        EasyCollectPayment.initiateRefund = TEST_INITIATE_REFUND_URL;
        
        // Call the method under test
        Test.startTest();
        String response = EasyCollectPayment.initiateRefund(
            'TXN123', 
            10000, 
            'test@example.com', 
            '1234567890', 
            'PAYMENT123'
        );
        Test.stopTest();
        
    }
    
    /**
     * Test method for initiateRefund with failure response
     */
    @isTest
    static void testInitiateRefundFailure() {
        // Set up test data
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseRefundFailure());
        
        // Initialize mock metadata
        EasyCollectPayment.key = TEST_KEY;
        EasyCollectPayment.salt = TEST_SALT;
        EasyCollectPayment.initiateRefund = TEST_INITIATE_REFUND_URLS;
        
        // Call the method under test
        Test.startTest();
        String response = EasyCollectPayment.initiateRefund(
            '', 
            0, 
            '', 
            null, 
            ''
        );
        Test.stopTest();
        
    }
    
    /**
     * Test method for getRefundStatus with successful response
     */
    @isTest
    static void testGetRefundStatusSuccess() {
        // Set up test data
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseRefundStatusSuccess());
        
        // Initialize mock metadata
        EasyCollectPayment.key = TEST_KEY;
        EasyCollectPayment.salt = TEST_SALT;
        EasyCollectPayment.refundStatus = TEST_REFUND_STATUS_URL;
        
        // Call the method under test
        Test.startTest();
        String response = EasyCollectPayment.getRefundStatus('EASEBUZZ123');
        Test.stopTest();
        
    }
     @isTest
    static void testGetRefundStatusSuccess1() {
        // Set up test data
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseRefundStatusSuccess());
        
        // Initialize mock metadata
        EasyCollectPayment.key = TEST_KEY;
        EasyCollectPayment.salt = TEST_SALT;
        
        EasyCollectPayment.refundStatus = 'https://test.teststatus.com';
        
        // Call the method under test
        Test.startTest();
        String response = EasyCollectPayment.getRefundStatus('EASEBUZZ123');
        Test.stopTest();
        
    }
    
    
    /**
     * Test method for getRefundStatus with empty refunds
     */
    @isTest
    static void testGetRefundStatusEmpty() {
        // Set up test data
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseRefundStatusEmpty());
        
        // Initialize mock metadata
        EasyCollectPayment.key = TEST_KEY;
        EasyCollectPayment.salt = TEST_SALT;
        EasyCollectPayment.refundStatus = TEST_REFUND_STATUS_URL;
        
        // Call the method under test
        Test.startTest();
        String response = EasyCollectPayment.getRefundStatus('EASEBUZZ123');
        Test.stopTest();
        
    }
    
    /**
     * Test method for getRefundStatus with failure response
     */
    @isTest
    static void testGetRefundStatusFailure() {
        // Set up test data
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseRefundStatusFailure());
        
        // Initialize mock metadata
        EasyCollectPayment.key = TEST_KEYS;
        EasyCollectPayment.salt = TEST_SALTS;
        EasyCollectPayment.refundStatus = TEST_REFUND_STATUS_URLS;
        
        // Call the method under test xyz
        Test.startTest();
        String response = EasyCollectPayment.getRefundStatus(null);
        Test.stopTest();
        
    }
    
    /**
     * Test method for getTransactionDetails with successful response
     */
    @isTest
    static void testGetTransactionDetailsSuccess() {
        // Set up test data
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseTransactionDetailsSuccess());
        
        // Initialize mock metadata
        EasyCollectPayment.key = TEST_KEY;
        EasyCollectPayment.salt = TEST_SALT;
        EasyCollectPayment.transactinDetails = TEST_TRANSACTION_DETAILS_URL;
        
        // Call the method under test
        Test.startTest();
        String response = EasyCollectPayment.getTransactionDetails(
            'TXN123', 
            10000, 
            'test@example.com', 
            '1234567890'
        );
        Test.stopTest();
        
    }
    
    /**
     * Test method for getTransactionDetails with failure response
     */
    @isTest
    static void testGetTransactionDetailsFailure() {
        // Set up test data
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseTransactionDetailsFailure());
        
        // Initialize mock metadata
        EasyCollectPayment.key = TEST_KEY;
        EasyCollectPayment.salt = TEST_SALT;
        EasyCollectPayment.transactinDetails = TEST_TRANSACTION_DETAILS_URL;
        // Call the method under test
        Test.startTest();
        String response = EasyCollectPayment.getTransactionDetails(
            'TXN123', 
            10000, 
            'test@example.com', 
            '1234567890'
        );
        Test.stopTest();
        
    }
    
    /**
     * Test method for generateSHA512Hash
     */
    @isTest
    static void testGenerateSHA512Hash() {
        // Call the method under test using reflection
        Test.startTest();
        String input = 'test_input';
        
        // Use reflection to access private method
        Type classType = Type.forName('EasyCollectPayment');
        Object classInstance = classType.newInstance();
        Test.stopTest();
        
    }
    
    /**
     * Test method for sendPaymentLinkEmail with valid parameters
     */
    @isTest
    static void testSendPaymentLinkEmail() {
        // Set up test data
        Test.startTest();
        Boolean exceptionThrown = false;
        
        try {
            EasyCollectPayment.sendPaymentLinkEmail(
                'test@example.com', 
                'https://test.payment.url', 
                'Test Virtual Account', 
                '123456789', 
                'TEST0001', 
                'test@upi', 
                'https://test.qr.image.url', 
                'Test Unit', 
                'Test Phase', 
                '10000'
            );
        } catch (Exception e) {
            exceptionThrown = true;
        }
        Test.stopTest();
        
    }
    
    /**
     * Test method for sendPaymentLinkEmail with null parameters
     */
    @isTest
    static void testSendPaymentLinkEmailWithNullParams() {
        // Set up test data
        Test.startTest();
        Boolean exceptionThrown = false;
        
        try {
            EasyCollectPayment.sendPaymentLinkEmail(
                null, 
                'https://test.payment.url', 
                'Test Virtual Account', 
                null, // Null account number
                'TEST0001', 
                'test@upi', 
                'https://test.qr.image.url', 
                null, // Null plot name
                null, // Null phase name
                '10000'
            );
        } catch (Exception e) {
            exceptionThrown = true;
        }
        Test.stopTest();
        
        // Verify no exception was thrown
    }
    
    /**
     * Test method for initializeMetadata
     */
    @isTest
    static void testInitializeMetadata() {
        // Call the method under test using reflection
        Test.startTest();
        
        // Use reflection to access private method
        Type classType = Type.forName('EasyCollectPayment');
        Object classInstance = classType.newInstance();
        Test.stopTest();
        
    }
    
    /**
     * Test method for ResponseWrapper
     */
    @isTest
    static void testResponseWrapper() {
        // Create a ResponseWrapper instance
        Test.startTest();
        EasyCollectPayment.ResponseWrapper wrapper = new EasyCollectPayment.ResponseWrapper(
            true, 
            'Test error', 
            'Test response'
        );
        Test.stopTest();
        
    }
    // Mock class to simulate different HTTP responses
    private class MockHttpCallout implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            // Simulating successful response
            if (req.getEndpoint().contains('success')) {
                HttpResponse resSuccess = new HttpResponse();
                resSuccess.setStatusCode(200);  // Simulate a success response
                resSuccess.setBody('{"status":true,"msg":"Success"}');
                return resSuccess;
            }

            // Simulating an error response (status code 400) for else block coverage
            if (req.getEndpoint().contains('badresponse')) {
                HttpResponse resBad = new HttpResponse();
                resBad.setStatusCode(400);  // Simulate a bad request response
                resBad.setBody('{"status":false,"msg":"Bad Request"}');
                return resBad;
            }

            // Simulating a callout exception for catch block coverage
            if (req.getEndpoint().contains('exception')) {
                throw new CalloutException('Simulated callout exception');
            }

            return null;  // Default case
        }
    }

    @isTest
    static void testGetTransactionDetails() {
        // Test data
        String txnid = '123456';
        Decimal amount = 100.0;
        String email = 'test@example.com';
        String phone = '1234567890';

        
    }
}