force-app/main/default/objects/Account/fields/PAN_Card__c.field-meta.xml
<CustomField>
    <fullName>PAN_Card__c</fullName>
    <label>PAN Card</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Additional_Charges__c/Additional_Charges__c.object-meta.xml
<CustomObject>
    <label>Additional Charges</label>
    <nameField>
        <label>Additional Charges Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Additional_Charges__c/fields/Additional_Charges__c.field-meta.xml
<CustomField>
    <fullName>Additional_Charges__c</fullName>
    <label>Additional Charges</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Plot</fullName>
            </value>
            <value>
                <fullName>Particulars</fullName>
            </value>
            <value>
                <fullName>Legal and Registration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Additional_Charges__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Additional Charges</relationshipLabel>
    <relationshipName>Additional_Charges</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Additional_Charges__c/fields/Plot__c.field-meta.xml
<CustomField>
    <fullName>Plot__c</fullName>
    <label>Plot</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Additional Charges</relationshipLabel>
    <relationshipName>Additional_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Aadhaar_Card__c.field-meta.xml
<CustomField>
    <fullName>Aadhaar_Card__c</fullName>
    <label>Aadhaar Card</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PAN_Card__c.field-meta.xml
<CustomField>
    <fullName>PAN_Card__c</fullName>
    <label>PAN Card</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sale_Value_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sale_Value_Amount__c</fullName>
    <label>Sale Value Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <label>Phase</label>
    <nameField>
        <label>Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Phase__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Phases</relationshipLabel>
    <relationshipName>Phases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote/fields/IsQuoteGenerated__c.field-meta.xml
<CustomField>
    <fullName>IsQuoteGenerated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsQuoteGenerated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Base_Price_Per_Sq_Yard__c.field-meta.xml
<CustomField>
    <fullName>Base_Price_Per_Sq_Yard__c</fullName>
    <label>Base Price Per Sq Yard</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/IsQuoteGenerated__c.field-meta.xml
<CustomField>
    <fullName>IsQuoteGenerated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsQuoteGenerated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Plot__c.field-meta.xml
<CustomField>
    <fullName>Plot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Total_Sale_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Sale_Value__c</fullName>
    <formula>Total_Unit_Cost__c +  Legal_And_Documentation_Charges__c +  Registration_Charges__c +  Corpus_Fund_and_Club_House_Payable__c + (Corpus_Fund_and_Club_House_Payable__c * 18/100)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Sale Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Phot Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Plots</relationshipLabel>
    <relationshipName>Plots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Management Blocked</fullName>
            </value>
            <value>
                <fullName>Mortgage</fullName>
            </value>
            <value>
                <fullName>Not For Sale</fullName>
            </value>
            <value>
                <fullName>Temp Blocked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/recordTypes/Plot.recordType-meta.xml
<RecordType>
    <fullName>Plot</fullName>
    <active>true</active>
    <label>Plot</label>
</RecordType>

force-app/main/default/classes/QuotationCostingSheetControllerTest.cls
@isTest
public class QuotationCostingSheetControllerTest {
    @testSetup
    static void setupTestData() {
         Account acc = new Account(Name = 'Test Account');
        insert acc;
        
        Contact con = new Contact(
            LastName = 'Test Contact',
            Email = 'test@example.com',
            Phone = '1234567890',
            Aadhaar_Card__c = '123412341234',
            PAN_Card__c = 'ABCDE1234F',
            Date_Of_Birth__c = Date.newInstance(1990, 5, 15),
            AccountId = acc.Id
        );
        insert con;
        
         Project__c proj = new Project__c(Name = 'Test Project', Active__c = true);
        insert proj;
        
        Phase__c phase = new Phase__c(Name = 'Test Phase', Project__c = proj.Id);
        insert phase;
        
        Unit__c unit = new Unit__c(
            Name = 'Test Plot',
            Status__c = 'Available',
           Contact__c=con.id,
            Phase__c = phase.Id
        );
        insert unit;
        
        List<Quote__c> quotes = new List<Quote__c>{
            new Quote__c( Base_Price_Per_Sq_Yard__c = 2000,Plot__c=unit.id,IsQuoteGenerated__c=false),
            new Quote__c( Base_Price_Per_Sq_Yard__c = 2500,Plot__c=unit.id,IsQuoteGenerated__c=false)
        };
        insert quotes;

        List<Opportunity> opps = new List<Opportunity>{
            new Opportunity(Name = 'Test Opp 1', StageName = 'Booked', CloseDate = Date.today(), Sale_Value_Amount__c = 50000,Contact__c=con.id, AccountId = acc.Id,Unit__c=unit.id),
            new Opportunity(Name = 'Test Opp 2', StageName = 'Booked', CloseDate = Date.today(), Sale_Value_Amount__c = 60000,Contact__c=con.id, AccountId = acc.Id,Unit__c=unit.id)
        };
        insert opps;
        
        Additional_Charges__c ac=new Additional_Charges__c();
        ac.Plot__c=unit.id;
        ac.Phase__c=phase.id;
        insert ac;
    }

    @isTest
    static void testSaveRecord() {
        List<Quote__c> quotes = [SELECT Id, Name, Total_Sale_Value__c FROM Quote__c];
        Test.startTest();
        List<Quote__c> result = QuotationCostingSheetController.SaveRecord(quotes);
        Test.stopTest();
        
      
    }

    @isTest
    static void testSaveOpportunityRecord() {
        List<Opportunity> opps = [SELECT Id, Name,Sale_Value_Amount__c FROM Opportunity];
        Test.startTest();
        QuotationCostingSheetController.SaveOpportunityRecord(opps);
        Test.stopTest();
    }

    @isTest
    static void testSubmitForApproval() {
        List<Quote__c> quotes = [SELECT Id FROM Quote__c LIMIT 1];
        Test.startTest();
        QuotationCostingSheetController.submitForApproval(quotes[0].Id);
        Test.stopTest();
    }

    @isTest
    static void testFinalizeQuote() {
        List<Quote__c> quotes = [SELECT Id FROM Quote__c];
        Test.startTest();
        QuotationCostingSheetController.FinalizeQuote(quotes);
        Test.stopTest();
    }

    @isTest
    static void testSendQuoteEmail() {
        List<Quote__c> quotes = [SELECT Id FROM Quote__c LIMIT 1];
        Test.startTest();
        QuotationCostingSheetController.sendQuoteEmail(quotes[0].Id, 'test@example.com', 'Test Quote');
        Test.stopTest();
    }

    @isTest
    static void testGetQuote() {
        List<Quote__c> quotes = [SELECT Id FROM Quote__c LIMIT 1];
        Test.startTest();
        QuotationCostingSheetController.lightningResponseWrapper response = QuotationCostingSheetController.getQuote(quotes[0].Id);
        Test.stopTest();
        
        
    }
    
      @isTest
    static void testIsQuoteGenerated() {
        List<Quote__c> quotes = [SELECT Id,IsQuoteGenerated__c FROM Quote__c LIMIT 1];
        quotes[0].IsQuoteGenerated__c=true;  
        update quotes;
        Test.startTest();
        QuotationCostingSheetController.lightningResponseWrapper response = QuotationCostingSheetController.getQuote(quotes[0].Id);
        Test.stopTest();
        
        
    }

    @isTest
    static void testGetOppDetails() {
        List<Opportunity> opps = [SELECT Id,Sale_Value_Amount__c FROM Opportunity LIMIT 1];
        Test.startTest();
        Opportunity opp = QuotationCostingSheetController.getOppDetails(opps[0].Id);
        QuotationCostingSheetController.sendEmail(opps[0].Id,'test plot','1000','1000','1000','1000');
        Test.stopTest();
        
    }
}