force-app/main/default/objects/Lead/fields/Parent_Lead__c.field-meta.xml
<CustomField>
    <fullName>Parent_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Lead Re-engagment</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Plot__c.field-meta.xml
<CustomField>
    <fullName>Plot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Phase__c</field>
            <operation>equals</operation>
            <valueField>Unit__c.Phase__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Plot__c/Lead_Plot__c.object-meta.xml
<CustomObject>
    <label>Lead Plot</label>
    <nameField>
        <displayFormat>LI-{0000}</displayFormat>
        <label>Lead Plot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Plots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Plot__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Lead Plots</relationshipLabel>
    <relationshipName>Lead_Plots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Plot__c/fields/Plot__c.field-meta.xml
<CustomField>
    <fullName>Plot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Lead Plots</relationshipLabel>
    <relationshipName>Lead_Plots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Base_Price_per_Sq_Ft__c.field-meta.xml
<CustomField>
    <fullName>Base_Price_per_Sq_Ft__c</fullName>
    <formula>Unit__r.Base_Price_per_Sq_Ft__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Base Price per Sq. Ft</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Plot_Size__c.field-meta.xml
<CustomField>
    <fullName>Plot_Size__c</fullName>
    <formula>Unit__r.Plot_Size__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plot Size</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <label>Phase</label>
    <nameField>
        <label>Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Phase__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Phases</relationshipLabel>
    <relationshipName>Phases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Plot__c.field-meta.xml
<CustomField>
    <fullName>Plot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Quote_Name__c.field-meta.xml
<CustomField>
    <fullName>Quote_Name__c</fullName>
    <formula>Name +  &apos; : &apos; +
Plot__r.Name + &apos; - &apos; +
TEXT(Lead__r.Salutation)  + &apos; &apos; +
Lead__r.FirstName + &apos; &apos; +
Lead__r.MiddleName + &apos; &apos; +
Lead__r.LastName</formula>
    <label>Quote Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Phot Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Base_Price_per_Sq_Ft__c.field-meta.xml
<CustomField>
    <fullName>Base_Price_per_Sq_Ft__c</fullName>
    <label>Base Price per Sq. Yard</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Plots</relationshipLabel>
    <relationshipName>Plots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Plot_Facing__c.field-meta.xml
<CustomField>
    <fullName>Plot_Facing__c</fullName>
    <label>Plot Facing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>North East</fullName>
            </value>
            <value>
                <fullName>North West</fullName>
            </value>
            <value>
                <fullName>South East</fullName>
            </value>
            <value>
                <fullName>South West</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Plot_Size__c.field-meta.xml
<CustomField>
    <fullName>Plot_Size__c</fullName>
    <label>Plot Size</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Management Blocked</fullName>
            </value>
            <value>
                <fullName>Mortgage</fullName>
            </value>
            <value>
                <fullName>Not For Sale</fullName>
            </value>
            <value>
                <fullName>Temp Blocked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit_Code__c.field-meta.xml
<CustomField>
    <fullName>Unit_Code__c</fullName>
    <label>Plot Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/recordTypes/Plot.recordType-meta.xml
<RecordType>
    <fullName>Plot</fullName>
    <active>true</active>
    <label>Plot</label>
</RecordType>

force-app/main/default/classes/leadQuoteGenerateController.cls
/**
* Author: Harshit Kumar Rai
* Description: For Plot Select and generation quote on lead
*/
public with sharing class leadQuoteGenerateController {
    @AuraEnabled(cacheable=true)
    public static List<Lead> getLeadDetails(Id leadId) {
        try {	
            List<Lead> lsitOfLead = [ SELECT Id, Project__r.Name, Phase__r.Name 
                                     FROM Lead WHERE Id = :leadId LIMIT 1];
            return lsitOfLead;
        } catch (Exception ex) {
            throw new AuraHandledException('Error fetching Lead details: ' + ex.getMessage());
        }
    }
    
    @AuraEnabled
    public static void sendEmail(String oppId) {
        try {
            List<Opportunity> oppList= [Select Id,Contact__c,Contact__r.Email From Opportunity Where Id=:oppId Limit 1];
            if(oppList!=null && oppList[0].Contact__c!=null){
                String recipientEmail = oppList[0].Contact__r.Email;
                Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                email.setToAddresses(new String[]{ recipientEmail });
                EmailTemplate template = [SELECT Id FROM EmailTemplate WHERE DeveloperName = 'Plot_Swapping' LIMIT 1];
                email.setTemplateId(template.Id);
                email.setTargetObjectId(oppList[0].Contact__c); 
                email.setWhatId(oppId);
                email.setTreatTargetObjectAsRecipient(false);
                Messaging.SendEmailResult[] results = Messaging.sendEmail(new Messaging.SingleEmailMessage[] { email });
                if (!results[0].isSuccess()) {
                    System.debug('Email failed to send: ' + results[0].getErrors()[0].getMessage());
                    throw new AuraHandledException(results[0].getErrors()[0].getMessage());
                } else {
                    System.debug('Email sent successfully to ' + recipientEmail);
                }
            }
        } catch (Exception ex) {
            throw new AuraHandledException('Error in sending email: ' + ex.getMessage());
        }
    }
    
    /**
* Searches records on the specified object based on a search key.
*
* @param searchKey The string to search for within the Name field.
* @param objectApiName The API name of the object to search (e.g., 'Unit__c').
* @return A list of sObjects that match the search criteria.
*/
    @AuraEnabled
    public static List<sObject> searchRecords(String searchKey, String objectApiName) {
        // Ensure searchKey is not null to avoid errors
        if (searchKey == null) {
            return new List<sObject>();
        }
        
        // Escape single quotes to prevent SOQL injection
        String escapedSearchKey = String.escapeSingleQuotes(searchKey);
        
        // Construct the dynamic SOQL query
        // NOTE: The field 'Name' is assumed to be present on the searched object.
        String query = 'SELECT Id, Name FROM ' + objectApiName +
            ' WHERE Status__c=\'Available\' AND Name LIKE \'%' + escapedSearchKey + '%\' LIMIT 10';
        
        system.debug(query);
        // Execute the query and return the results
        List<sObject> records = Database.query(query);
        return records;
    }
    
    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getUnitAndLeadDetails(Id unitId) {
        if (unitId == null) {
            return null;
        }
        
        try {
            // Query Unit__c record along with its related Lead__c
            Unit__c unitRecord = [
                SELECT Id, Name, Unit_Code__c, Plot_Facing__c, Plot_Size__c, 
                Status__c, Base_Price_per_Sq_Ft__c, 
                (SELECT Id, FirstName, LastName, Email FROM Leads__r LIMIT 1) 
                FROM Unit__c 
                WHERE Id = :unitId
                LIMIT 1
            ];
            
            Map<String, Object> response = new Map<String, Object>();
            response.put('unit', unitRecord);
            
            // If a related lead exists, include it in the response
            if (unitRecord.Leads__r != null && !unitRecord.Leads__r.isEmpty()) {
                response.put('lead', unitRecord.Leads__r[0]);
            } else {
                response.put('lead', null);
            }
            
            return response;
            
        } catch (Exception e) {
            throw new AuraHandledException('Error fetching Unit and Lead details: ' + e.getMessage());
        }
    }
    
    @AuraEnabled
    public static void saveLeadPlotRecords(List<Lead_Plot__c> leadPlotRecords, List<Quote__c> quoteRecords) {
        try {
            if (leadPlotRecords != null && !leadPlotRecords.isEmpty()) {
                insert leadPlotRecords;
            }
            if (quoteRecords != null && !quoteRecords.isEmpty()) {
                insert quoteRecords;
            }
        } catch (Exception ex) {
            throw new AuraHandledException('Error creating Lead_Plot__c records: ' + ex.getMessage());
        }
    }
    
    @AuraEnabled
    public static List<Quote__c> saveLeadQuoteRecords(List<Quote__c> quoteRecords) {
        try {
            if (quoteRecords != null && !quoteRecords.isEmpty()) {
                insert quoteRecords;
                Set<Id> quoteIds = new Set<Id>();
                for (Quote__c quote : quoteRecords) {
                    quoteIds.add(quote.Id);
                }
                return [SELECT Id, Name, Quote_Name__c, Plot__r.Name, Plot__r.Plot_Size__c  
                        FROM Quote__c WHERE Id IN :quoteIds];
            }
            return null;
        } catch (Exception ex) {
            throw new AuraHandledException('Error creating Quote__c records: ' + ex.getMessage());
        }
    }
    
    @AuraEnabled
    public static List<Opportunity> saveOpportunity(List<Opportunity> oppRecords) {
        try {
            if (oppRecords != null && !oppRecords.isEmpty()) {
                update oppRecords;
                return oppRecords;
            }
            return null;
        } catch (Exception ex) {
            throw new AuraHandledException('Error in updating opportunity plot details: ' + ex.getMessage());
        }
    }
}