force-app/main/default/objects/Lead/fields/Plot__c.field-meta.xml
<CustomField>
    <fullName>Plot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Phase__c</field>
            <operation>equals</operation>
            <valueField>Unit__c.Phase__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Base_Price_per_Sq_Ft__c.field-meta.xml
<CustomField>
    <fullName>Base_Price_per_Sq_Ft__c</fullName>
    <formula>Unit__r.Base_Price_per_Sq_Ft__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Base Price per Sq. Ft</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Plot_Size__c.field-meta.xml
<CustomField>
    <fullName>Plot_Size__c</fullName>
    <formula>Unit__r.Plot_Size__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plot Size</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Corpus_Fund_and_Club_House_Payable__c.field-meta.xml
<CustomField>
    <fullName>Corpus_Fund_and_Club_House_Payable__c</fullName>
    <label>Corpus Fund and Club House Payable</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Legal_And_Documentation_Charges__c.field-meta.xml
<CustomField>
    <fullName>Legal_And_Documentation_Charges__c</fullName>
    <label>Legal And Documentation Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Plot__c.field-meta.xml
<CustomField>
    <fullName>Plot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Registration_Charges__c.field-meta.xml
<CustomField>
    <fullName>Registration_Charges__c</fullName>
    <label>Registration Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Time_To_Pay_In_Days__c.field-meta.xml
<CustomField>
    <fullName>Time_To_Pay_In_Days__c</fullName>
    <label>Time To Pay In Days</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Phot Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Base_Price_per_Sq_Ft__c.field-meta.xml
<CustomField>
    <fullName>Base_Price_per_Sq_Ft__c</fullName>
    <label>Base Price per Sq. Yard</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Flat_Number__c.field-meta.xml
<CustomField>
    <fullName>Flat_Number__c</fullName>
    <label>Flat Number</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Floor_Number__c.field-meta.xml
<CustomField>
    <fullName>Floor_Number__c</fullName>
    <label>Floor Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Plot_Facing__c.field-meta.xml
<CustomField>
    <fullName>Plot_Facing__c</fullName>
    <label>Plot Facing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>North East</fullName>
            </value>
            <value>
                <fullName>North West</fullName>
            </value>
            <value>
                <fullName>South East</fullName>
            </value>
            <value>
                <fullName>South West</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Plot_Size__c.field-meta.xml
<CustomField>
    <fullName>Plot_Size__c</fullName>
    <label>Plot Size</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit_Code__c.field-meta.xml
<CustomField>
    <fullName>Unit_Code__c</fullName>
    <label>Plot Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/recordTypes/Plot.recordType-meta.xml
<RecordType>
    <fullName>Plot</fullName>
    <active>true</active>
    <label>Plot</label>
</RecordType>

force-app/main/default/classes/QuotePdfControllerTest.cls
@isTest
private class QuotePdfControllerTest {

    // Helper method to create a test Quote__c record
    private static Quote__c createTestQuote() {
        // Create a sample Opportunity
        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Prospecting',
            CloseDate = Date.today()
            //AccountId = UserInfo.getUserId()
        );
        insert opp;

        // Create a sample Lead
        Lead lead = new Lead(
            FirstName = 'John',
            LastName = 'Doe',
            Company = 'Test Company',
            Email = 'johndoe@test.com',
            Phone = '1234567890'
        );
        insert lead;

        // Create a sample Plot__c record
        Unit__c plot = new Unit__c(
            Name = 'Test Plot',
            Plot_Facing__c = 'North',
            Plot_Size__c = 1200,
            Flat_Number__c = 245,
            Floor_Number__c = 1,
            Unit_Code__c = 765,
            Base_Price_per_Sq_Ft__c = 2000
        );
        insert plot;

        // Create a test Quote__c record
        Quote__c quote = new Quote__c(
            Lead__c = lead.Id,
            Opportunity__c = opp.Id,
            Plot__c = plot.Id,
            Corpus_Fund_and_Club_House_Payable__c = 50000.0,
            Legal_And_Documentation_Charges__c = 1000.0,
            Registration_Charges__c = 2000.0,
            Time_To_Pay_In_Days__c = 30
        );
        insert quote;

        return quote;
    }

    // Test method for QuotePdfController constructor
    @isTest
    static void testQuotePdfController() {
        // Create a test Quote__c record
        Quote__c quoteRecord = createTestQuote();

        // Simulate the Standard Controller by passing in the ID of the Quote__c record
        ApexPages.StandardController stdController = new ApexPages.StandardController(quoteRecord);
        
        // Initialize the QuotePdfController with the Standard Controller
        QuotePdfController controller = new QuotePdfController(stdController);

        // Check if the controller's fields are populated correctly (using debug to check output)
        System.debug('Date of Booking: ' + controller.dateOfBooking);
        System.debug('GST Amount: ' + controller.gstAmount);
        System.debug('Final Corpus: ' + controller.finalCorpus);
        System.debug('Final Legal and Registration Charges: ' + controller.finalLegalAndRegistrationCharges);
        System.debug('Time in Days: ' + controller.timeDays);
        
        // Simulate empty or null values for some fields to test the behavior
        Quote__c quoteRecord2 = new Quote__c(
            Lead__c = null,
            Opportunity__c = null,
            Plot__c = null,
            Corpus_Fund_and_Club_House_Payable__c = null,
            Legal_And_Documentation_Charges__c = null,
            Registration_Charges__c = null,
            Time_To_Pay_In_Days__c = null
        );
        insert quoteRecord2;

        // Simulate the Standard Controller with the second Quote record
        stdController = new ApexPages.StandardController(quoteRecord2);
        
        // Initialize the QuotePdfController with the second Quote record
        QuotePdfController controller2 = new QuotePdfController(stdController);

        // Check if the controller's fields are populated correctly for the second record (using debug)
        System.debug('Date of Booking: ' + controller2.dateOfBooking);
        System.debug('GST Amount: ' + controller2.gstAmount);
        System.debug('Final Corpus: ' + controller2.finalCorpus);
        System.debug('Final Legal and Registration Charges: ' + controller2.finalLegalAndRegistrationCharges);
        System.debug('Time in Days: ' + controller2.timeDays);
    }
}