force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <label>Phase</label>
    <nameField>
        <label>Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Phot Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Base_Price_per_Sq_Ft__c.field-meta.xml
<CustomField>
    <fullName>Base_Price_per_Sq_Ft__c</fullName>
    <label>Base Price per Sq. Yard</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Plot_Facing__c.field-meta.xml
<CustomField>
    <fullName>Plot_Facing__c</fullName>
    <label>Plot Facing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>North East</fullName>
            </value>
            <value>
                <fullName>North West</fullName>
            </value>
            <value>
                <fullName>South East</fullName>
            </value>
            <value>
                <fullName>South West</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Plot_Price__c.field-meta.xml
<CustomField>
    <fullName>Plot_Price__c</fullName>
    <label>Final Plot Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Plot_Size__c.field-meta.xml
<CustomField>
    <fullName>Plot_Size__c</fullName>
    <label>Plot Size</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Management Blocked</fullName>
            </value>
            <value>
                <fullName>Mortgage</fullName>
            </value>
            <value>
                <fullName>Not For Sale</fullName>
            </value>
            <value>
                <fullName>Temp Blocked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit_Inventory_Specifications__c/Unit_Inventory_Specifications__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Unit Inventory Specifications</label>
</CustomObject>

force-app/main/default/objects/Unit_Inventory_Specifications__c/fields/Available_Plot__c.field-meta.xml
<CustomField>
    <fullName>Available_Plot__c</fullName>
    <description>Color of Available Plot, Value should be in HEX</description>
    <label>Available Plot</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit_Inventory_Specifications__c/fields/Blocked_Plot__c.field-meta.xml
<CustomField>
    <fullName>Blocked_Plot__c</fullName>
    <description>Color of Blocked Plot, Value should be in HEX</description>
    <label>Blocked Plot</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit_Inventory_Specifications__c/fields/Booked_Plot__c.field-meta.xml
<CustomField>
    <fullName>Booked_Plot__c</fullName>
    <description>Color of Booked Plot, Value should be in HEX</description>
    <label>Booked Plot</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit_Inventory_Specifications__c/fields/Garden__c.field-meta.xml
<CustomField>
    <fullName>Garden__c</fullName>
    <description>Color of Garden, Value should be in HEX</description>
    <label>Garden</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit_Inventory_Specifications__c/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <description>Cell Height</description>
    <label>Height</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit_Inventory_Specifications__c/fields/Hold_Plot__c.field-meta.xml
<CustomField>
    <fullName>Hold_Plot__c</fullName>
    <description>Color of Hold Plot, Value should be in HEX</description>
    <label>Hold Plot</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit_Inventory_Specifications__c/fields/Management_Blocked_Plot__c.field-meta.xml
<CustomField>
    <fullName>Management_Blocked_Plot__c</fullName>
    <description>Color of Management Blocked Plot, Value should be in HEX</description>
    <label>Management Blocked Plot</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit_Inventory_Specifications__c/fields/Mortgage_Plot__c.field-meta.xml
<CustomField>
    <fullName>Mortgage_Plot__c</fullName>
    <description>Color of Mortgage Plot, Value should be in HEX</description>
    <label>Mortgage Plot</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit_Inventory_Specifications__c/fields/Multi_Select_Color__c.field-meta.xml
<CustomField>
    <fullName>Multi_Select_Color__c</fullName>
    <label>Multi Select Color</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit_Inventory_Specifications__c/fields/Not_For_Sale_Plot__c.field-meta.xml
<CustomField>
    <fullName>Not_For_Sale_Plot__c</fullName>
    <description>Color of Not For Sale Plot, Value should be in HEX</description>
    <label>Not For Sale Plot</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit_Inventory_Specifications__c/fields/Registered_Plot__c.field-meta.xml
<CustomField>
    <fullName>Registered_Plot__c</fullName>
    <description>Color of Registered Plot, Value should be in HEX</description>
    <label>Registered Plot</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit_Inventory_Specifications__c/fields/Road__c.field-meta.xml
<CustomField>
    <fullName>Road__c</fullName>
    <description>Color of Road, Value should be in HEX</description>
    <label>Road</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit_Inventory_Specifications__c/fields/Sold_Plot__c.field-meta.xml
<CustomField>
    <fullName>Sold_Plot__c</fullName>
    <description>Color of Sold Plot, Value should be in HEX</description>
    <label>Sold Plot</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit_Inventory_Specifications__c/fields/Temp_Blocked_Plot__c.field-meta.xml
<CustomField>
    <fullName>Temp_Blocked_Plot__c</fullName>
    <description>Color of Temp Blocked Plot, Value should be in HEX</description>
    <label>Temp Blocked Plot</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit_Inventory_Specifications__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <description>Cell Width</description>
    <label>Width</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UnitInventoryScreenController.cls
public with sharing class UnitInventoryScreenController {
    @AuraEnabled(cacheable=true)
    public static List<Unit_Inventory_Specifications__c> getTableDimensions() {
        return [SELECT Name, Height__c, Width__c, Available_Plot__c, Booked_Plot__c, Hold_Plot__c, Road__c, Garden__c, Blocked_Plot__c, Management_Blocked_Plot__c,
                Mortgage_Plot__c, Not_For_Sale_Plot__c, Registered_Plot__c, Sold_Plot__c, Temp_Blocked_Plot__c, Multi_Select_Color__c
                FROM Unit_Inventory_Specifications__c 
                WHERE Name = 'Box Specification'];
    }
    @AuraEnabled(cacheable=true)
    public static List<Unit__c> searchPlots(String plotName, String phaseId) {
        // Query to search for plots by name
        if (String.isNotBlank(plotName) && plotName.length() >= 3) {
            String searchTerm = '%' + plotName + '%';  // Wildcard for partial matching
            List<Unit__c> plots = [SELECT Id, Name, Base_Price_per_Sq_Ft__c, Plot_Price__c, RecordType.Name, Status__c, Phase__r.Name, Plot_Size__c, Plot_Facing__c
                                    FROM Unit__c 
                                    WHERE Name LIKE :searchTerm AND Phase__c =: phaseId LIMIT 50];
            return plots;
        }
        // If no search term is provided or less than 3 characters, return first 4 plots
        List<Unit__c> plots = [SELECT Id, Name, Base_Price_per_Sq_Ft__c, Plot_Price__c, RecordType.Name, Status__c, Phase__r.Name, Plot_Size__c, Plot_Facing__c
                                FROM Unit__c 
                                WHERE Phase__c =: phaseId LIMIT 50];  // Fetch first 4 plots
        return plots;
    }
    @AuraEnabled
    public static boolean updatePlotStatus(Map<Id, String> plotStatusMap) {
        if (plotStatusMap == null || plotStatusMap.isEmpty()) {
            return false;
        }
        List<Unit__c> plotsToUpdate = new List<Unit__c>();
        for (Id plotId : plotStatusMap.keySet()) {
            plotsToUpdate.add(new Unit__c(Id = plotId, Status__c = plotStatusMap.get(plotId)));
        }
        try {
            if (!plotsToUpdate.isEmpty()) {
                update plotsToUpdate;  // Bulk update in a single DML operation
            }
            return true;
        } catch (DmlException e) {
            System.debug('Error updating plots: ' + e.getMessage());
            return false;
        }
    }
    @AuraEnabled
    public static Unit__c getCellData(String plotId) {
        Unit__c plotData = [SELECT Id, Name, Base_Price_per_Sq_Ft__c, Plot_Price__c, RecordType.Name, Status__c, Phase__r.Name, Plot_Size__c, Plot_Facing__c
                                FROM Unit__c 
                                WHERE Id =: plotId];
        return plotData;
    }
}