force-app/main/default/objects/Opportunity/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <formula>Unit__r.Bank_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bank Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Collected_Amount__c.field-meta.xml
<CustomField>
    <fullName>Collected_Amount__c</fullName>
    <label>Collected Amount</label>
    <summarizedField>Payment__c.Payment_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Payment__c.Approval_Status__c</field>
        <operation>equals</operation>
        <value>Approved</value>
    </summaryFilterItems>
    <summaryForeignKey>Payment__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Outstanding_Amount__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Amount__c</fullName>
    <formula>Sale_Value_Amount__c -  Total_Collected_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Outstanding Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sale_Value_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sale_Value_Amount__c</fullName>
    <label>Sale Value Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Virtual_Account_IFSC__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Account_IFSC__c</fullName>
    <formula>Unit__r.Virtual_Account_IFSC__c</formula>
    <label>Virtual Account IFSC</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Virtual_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Account_Number__c</fullName>
    <formula>Unit__r.Virtual_Account_Number__c</formula>
    <label>Virtual Account Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Phot Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Virtual_Account_IFSC__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Account_IFSC__c</fullName>
    <label>Virtual Account IFSC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Virtual_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Account_Number__c</fullName>
    <label>Virtual Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/demandLetterPdfController.cls
public class demandLetterPdfController {
	
    public Opportunity opportunityRecord { get; set; }
    public OpportunityContactRole OpportunityContactRolesRecord { get; set; }
    public String balanceAmountInWords { get; set; }
    
    public demandLetterPdfController(ApexPages.StandardController stdController) {
        
        Id opportunityId = ApexPages.currentPage().getParameters().get('Id');
        System.debug('Quote Id-->>'+opportunityId);
       List<Opportunity> opportunityList = [SELECT  id,Name,Unit__r.Name,Unit__r.Bank_Name__c,Unit__r.Virtual_Account_IFSC__c,Unit__r.Virtual_Account_Number__c,
                                            Sale_Value_Amount__c, Collected_Amount__c, Outstanding_Amount__c
                                            FROM Opportunity WHERE Id = :opportunityId LIMIT 1];
        
         if(!opportunityList.isEmpty()){
            opportunityRecord=opportunityList[0];
        }
        if(opportunityRecord.Outstanding_Amount__c>0){
            balanceAmountInWords = NumberToCharacter.getNumberTOWordConvertion(opportunityRecord.Outstanding_Amount__c);
        }else{
            balanceAmountInWords='-';
        }
        
        
         List<OpportunityContactRole> OpportunityContactRolesList = [SELECT Id,ContactId, Contact.Name, Contact.Email, Contact.Phone ,Contact.Permanent_Address__City__s,
                                             Contact.Permanent_Address__CountryCode__s,Contact.Permanent_Address__StateCode__s,Contact.Permanent_Address__PostalCode__s,
                                             Contact.Permanent_Address__Street__s ,OpportunityId
            								 FROM OpportunityContactRole WHERE IsPrimary = TRUE and OpportunityId=: opportunityId LIMIT 1];
        
          if(!OpportunityContactRolesList.isEmpty()){
            OpportunityContactRolesRecord=OpportunityContactRolesList[0];
        }
        
        system.debug('opportunityList--->'+opportunityList);
      
    }
    
}