force-app/main/default/objects/Opportunity/fields/Base_Price_per_Sq_Ft__c.field-meta.xml
<CustomField>
    <fullName>Base_Price_per_Sq_Ft__c</fullName>
    <formula>Unit__r.Base_Price_per_Sq_Ft__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Base Price per Sq. Ft</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Plot_Dimension__c.field-meta.xml
<CustomField>
    <fullName>Plot_Dimension__c</fullName>
    <label>Plot Dimension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Head__c.field-meta.xml
<CustomField>
    <fullName>Sales_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <label>Phase</label>
    <nameField>
        <label>Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Phase__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Phases</relationshipLabel>
    <relationshipName>Phases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Plot</fullName>
            </value>
            <value>
                <fullName>Apartment</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Sales_Head__c.field-meta.xml
<CustomField>
    <fullName>Sales_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <label>GST</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Plot_Dimension__c.field-meta.xml
<CustomField>
    <fullName>Plot_Dimension__c</fullName>
    <label>Plot Dimension</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Plot_Saleable_Area_In_Sqft__c.field-meta.xml
<CustomField>
    <fullName>Plot_Saleable_Area_In_Sqft__c</fullName>
    <label>Plot Saleable Area (In Sqft)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Plot_Saleable_Area_In_Sqm__c.field-meta.xml
<CustomField>
    <fullName>Plot_Saleable_Area_In_Sqm__c</fullName>
    <label>Plot Saleable Area (In Sqm)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Quote_End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Quote_End_Date_Time__c</fullName>
    <label>Quote End Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Sales_Head__c.field-meta.xml
<CustomField>
    <fullName>Sales_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Phot Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Base_Price_per_Sq_Ft__c.field-meta.xml
<CustomField>
    <fullName>Base_Price_per_Sq_Ft__c</fullName>
    <label>Base Price per Sq. Yard</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Plot_Dimension__c.field-meta.xml
<CustomField>
    <fullName>Plot_Dimension__c</fullName>
    <label>Plot Dimension</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Plot_Facing__c.field-meta.xml
<CustomField>
    <fullName>Plot_Facing__c</fullName>
    <label>Plot Facing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>North East</fullName>
            </value>
            <value>
                <fullName>North West</fullName>
            </value>
            <value>
                <fullName>South East</fullName>
            </value>
            <value>
                <fullName>South West</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Management Blocked</fullName>
            </value>
            <value>
                <fullName>Mortgage</fullName>
            </value>
            <value>
                <fullName>Not For Sale</fullName>
            </value>
            <value>
                <fullName>Temp Blocked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit_Code__c.field-meta.xml
<CustomField>
    <fullName>Unit_Code__c</fullName>
    <label>Plot Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GenerateQuote.cls
public class GenerateQuote {
    
        @AuraEnabled
    public static LightningResponse generateQuote(String recordId,String strunitId,String strPhaseId,String strTowerId,String strProjectId){
        try {
            Decimal gstValue ;
            List<Unit__c> unitDetail = new List<Unit__c>();
            List<Opportunity> oppDetail = new List<Opportunity>();
            List<Phase__c> pahseDetail = new List<Phase__c>();
            List<Project__c> projectDetail = new List<Project__c>(); 
            oppDetail = [SELECT Id,Name,Account.Name FROM Opportunity WHERE Id=:recordId];
            unitDetail = [SELECT Id,Name,Base_Price_per_Sq_Ft__c,Unit_Code__c,
            Plot_Facing__c,Project__r.Project_Type__c FROM Unit__c WHERE Id=:strunitId];
            pahseDetail = [SELECT Id,Name FROM Phase__c WHERE Id=:strPhaseId];
            projectDetail = [SELECT Id,Sales_Head__c FROM Project__c WHERE Id=:strProjectId];
            //gstValue = pahseDetail[0].GST__c ;
            
            Quote newGeneratedQuote = new Quote ();
            newGeneratedQuote.Name = oppDetail[0].Name + '-Quote';
            newGeneratedQuote.Status__c = 'Draft';
            newGeneratedQuote.Sales_Head__c = projectDetail[0].Sales_Head__c!=null? projectDetail[0].Sales_Head__c:null ;
            //newGeneratedQuote.CustomerName__c = oppDetail[0].Account.Name;
            //newGeneratedQuote.BasePriceperSqFt__c = unitDetail[0].Base_Price_per_Sq_Ft__c!=null? unitDetail[0].Base_Price_per_Sq_Ft__c :0;
            //newGeneratedQuote.Tower__c = strTowerId;
            newGeneratedQuote.Project__c = strProjectId;
            newGeneratedQuote.Phase__c = strPhaseId;
            newGeneratedQuote.OpportunityId = recordId;
            newGeneratedQuote.Unit__c = unitDetail[0].Id;
            //newGeneratedQuote.GST__c = gstValue;
            //newGeneratedQuote.Corner_Plot__c = unitDetail[0].Corner_Plot__c;
            //newGeneratedQuote.Plot_Saleable_Area_In_Sqft__c = unitDetail[0].Plot_Saleable_Area_In_Sqft__c!=null? unitDetail[0].Plot_Saleable_Area_In_Sqft__c :0;
            //newGeneratedQuote.Plot_Saleable_Area_In_Sqm__c = unitDetail[0].Plot_Saleable_Area_In_Sqm__c!=null? unitDetail[0].Plot_Saleable_Area_In_Sqm__c :0;
            //newGeneratedQuote.BasePriceperSqFt__c = unitDetail[0].Base_Price_per_Sq_Ft__c!=null? unitDetail[0].Base_Price_per_Sq_Ft__c :0;
            //newGeneratedQuote.Facing__c = unitDetail[0].Facing__c!=null? unitDetail[0].Facing__c :'';
            //newGeneratedQuote.Plot_Dimension__c = unitDetail[0].Plot_Dimension__c!=null? unitDetail[0].Plot_Dimension__c :'';
            //newGeneratedQuote.Carpet_Area_In_sqft__c = unitDetail[0].Carpet_Area_In_sqft__c!=null? unitDetail[0].Carpet_Area_In_sqft__c :0; 
            //newGeneratedQuote.Carpet_Area_In_sqm__c = unitDetail[0].Carpet_Area_In_sqm__c!=null? unitDetail[0].Carpet_Area_In_sqm__c :0; 
            //newGeneratedQuote.Private_Garden_Area_In_Sqm__c = unitDetail[0].Private_Garden_Area_In_Sqm__c!=null? unitDetail[0].Private_Garden_Area_In_Sqm__c :0;  
            //newGeneratedQuote.Private_Garden_Area_In_Sqft__c = unitDetail[0].Private_Garden_Area_In_Sqft__c!=null? unitDetail[0].Private_Garden_Area_In_Sqft__c :0; 
            //newGeneratedQuote.UnitCode__c = unitDetail[0].Unit_Code__c;
            
            DateTime currentDateTime = DateTime.now();
            DateTime futureDateTime = currentDateTime.addHours(24);
            newGeneratedQuote.Quote_End_Date_Time__c = futureDateTime;
            insert newGeneratedQuote;
            LightningResponse response = new LightningResponse();
            response.isSuccess = true;
            response.quoteId = newGeneratedQuote.Id;
            return response;
        } catch (Exception e) {
            System.debug('e line---'+e.getLineNumber());
            System.debug('e message---'+e.getMessage());
            LightningResponse response = new LightningResponse();
            response.isSuccess=false;
            response.message=e.getMessage();
            return response;
        }
    }
    
        public  class LightningResponse {
        @AuraEnabled
        public   Boolean isSuccess {get;set;}
        @AuraEnabled
        public   String message {get;set;}
        @AuraEnabled
        public  set<String>  setFieldsname {get;set;}
        @AuraEnabled
        public  List<Integer>  flatList {get;set;}
         @AuraEnabled
        public String quoteId {get;set;}
    }

}