force-app/main/default/objects/Opportunity/fields/Board_Of_Resolution_Authority_Person__c.field-meta.xml
<CustomField>
    <fullName>Board_Of_Resolution_Authority_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Board Of Resolution Authority Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Collected_Amount__c.field-meta.xml
<CustomField>
    <fullName>Collected_Amount__c</fullName>
    <label>Collected Amount</label>
    <summarizedField>Payment__c.Payment_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Payment__c.Approval_Status__c</field>
        <operation>equals</operation>
        <value>Approved</value>
    </summaryFilterItems>
    <summaryForeignKey>Payment__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Outstanding_Amount__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Amount__c</fullName>
    <formula>Sale_Value_Amount__c -  Total_Collected_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Outstanding Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sale_Value_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sale_Value_Amount__c</fullName>
    <label>Sale Value Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Phot Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Board_Of_Resolution_Authority_Person__c.field-meta.xml
<CustomField>
    <fullName>Board_Of_Resolution_Authority_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Board Of Resolution Authority Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Plots1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BoardOfResolutionController.cls
public class BoardOfResolutionController {
	
    public Opportunity opportunityRecord { get; set; }
    public String balanceAmountInWords { get; set; }
    
    public BoardOfResolutionController(ApexPages.StandardController stdController) {
        
        Id opportunityId = ApexPages.currentPage().getParameters().get('Id');
        System.debug('Quote Id-->>'+opportunityId);
       List<Opportunity> opportunityList = [SELECT  id,Name,Unit__r.Name,Unit__r.Address__City__s,Unit__r.Address__CountryCode__s,Unit__r.Address__PostalCode__s,
                                            Unit__r.Address__StateCode__s,Unit__r.Address__Street__s,Board_Of_Resolution_Authority_Person__c,
                                            Board_Of_Resolution_Authority_Person__r.Name,
                                            Sale_Value_Amount__c, Collected_Amount__c, Outstanding_Amount__c
                                            FROM Opportunity WHERE Id = :opportunityId LIMIT 1];
        
         if(!opportunityList.isEmpty()){
            opportunityRecord=opportunityList[0];
        }
        if(opportunityRecord.Outstanding_Amount__c>0){
            balanceAmountInWords = NumberToCharacter.getNumberTOWordConvertion(opportunityRecord.Outstanding_Amount__c);
        }else{
            balanceAmountInWords='-';
        }
        system.debug('opportunityList--->'+opportunityList);
      
    }
    
}