force-app/main/default/objects/Opportunity/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <formula>Contact__r.FirstName + &apos; &apos;+ Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Mode__c.field-meta.xml
<CustomField>
    <fullName>Payment_Mode__c</fullName>
    <label>Payment Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>NEFT</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>UPI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Plot_Name__c.field-meta.xml
<CustomField>
    <fullName>Plot_Name__c</fullName>
    <formula>Unit__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plot Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payer Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/InstaCollect_Transaction_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>InstaCollect_Transaction_Date_Time__c</fullName>
    <label>InstaCollect Transaction Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/InstaCollect_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>InstaCollect_Transaction_Id__c</fullName>
    <label>InstaCollect Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Merchant_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Transaction_Id__c</fullName>
    <label>Merchant Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Remitter_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Remitter_Full_Name__c</fullName>
    <label>Remitter Full Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <label>Phase</label>
    <nameField>
        <label>Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Phase__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Phases</relationshipLabel>
    <relationshipName>Phases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Phot Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PaymentReceiptController.cls
/*
*********************************************************
Apex Class Name    : PaymentReceiptController
Created Date       : 18th March 2024
@description       : For Payment Reciept Generation
@author            : Harshit Kumar Rai
*********************************************************
*/
public with sharing class PaymentReceiptController{
    
    public String todayDate { get; set; }
    public String customerName { get; set; }
    public String referenceId { get; set; }
    public String rupeesInWord { get ; set; }
    public Payment__c paymentRecord { get; set; }
    public String paymentDate { get; set; }
    
     /*
    *********************************************************
    @Constructor Name  : PaymentReceiptController
    @author            : Harshit Kumar Rai
    @description       : Initializes class and retrieves payment recieved details
    @param             : ApexPages.StandardController stdController - Standard controller for Payment__c
    ****
	*/
    
    public PaymentReceiptController(ApexPages.StandardController stdController) {
        String paymentId= Apexpages.currentPage().getParameters().get('id');
        List<Payment__c> paymentRecordList = [SELECT Id, Payment_Amount__c, Opportunity__r.Name, Contact_Name__r.Name, 
                                              Remitter_Full_Name__c, Opportunity__r.Plot_Name__c,
                                              Opportunity__r.Unit__r.Project__r.Name, Opportunity__r.Unit__r.Phase__r.Name, 
                                              Payment_Mode__c, InstaCollect_Transaction_Id__c, 
                                              Merchant_Transaction_Id__c, Payment_Created_Date__c, 
                                              InstaCollect_Transaction_Date_Time__c 
                                              FROM Payment__c Where Id=:paymentId];
        
        if(paymentRecordList!=null && !paymentRecordList.isEmpty()){
            paymentRecord=paymentRecordList[0];
            todayDate=String.ValueOf(DateTime.now().format('dd-MM-yyyy'));
            rupeesInWord=NumberToCharacter.getNumberTOWordConvertion(paymentRecord.Payment_Amount__c);
            if(paymentRecord.InstaCollect_Transaction_Id__c!=null){
                customerName=paymentRecord.Remitter_Full_Name__c;
                referenceId=paymentRecord.InstaCollect_Transaction_Id__c;
                paymentDate=String.ValueOf(paymentRecord.InstaCollect_Transaction_Date_Time__c.format('dd-MM-yyyy'));
            }else if(paymentRecord.Merchant_Transaction_Id__c!=null){
                customerName=paymentRecord.Contact_Name__r.Name;
                referenceId=paymentRecord.Merchant_Transaction_Id__c;
                paymentDate=String.ValueOf(paymentRecord.Payment_Created_Date__c.format('dd-MM-yyyy'));
            }
        }
        
    }
    
}