force-app/main/default/objects/Opportunity/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Virtual_Account_IFSC__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Account_IFSC__c</fullName>
    <formula>Unit__r.Virtual_Account_IFSC__c</formula>
    <label>Virtual Account IFSC</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Virtual_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Account_Name__c</fullName>
    <formula>Unit__r.Virtual_Account_Name__c</formula>
    <label>Virtual Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Virtual_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Account_Number__c</fullName>
    <formula>Unit__r.Virtual_Account_Number__c</formula>
    <label>Virtual Account Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <label>Phase</label>
    <nameField>
        <label>Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Phot Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unique_Request_Number__c.field-meta.xml
<CustomField>
    <fullName>Unique_Request_Number__c</fullName>
    <label>Unique Request Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/UPI_QR_Image__c.field-meta.xml
<CustomField>
    <fullName>UPI_QR_Image__c</fullName>
    <label>UPI QR Image</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/UPI_QR_PDF__c.field-meta.xml
<CustomField>
    <fullName>UPI_QR_PDF__c</fullName>
    <label>UPI QR PDF</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Virtual_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Account_Id__c</fullName>
    <label>Virtual Account Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Virtual_Account_IFSC__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Account_IFSC__c</fullName>
    <label>Virtual Account IFSC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Virtual_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Account_Name__c</fullName>
    <label>Virtual Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Virtual_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Account_Number__c</fullName>
    <label>Virtual Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Virtual_Account_UPI__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Account_UPI__c</fullName>
    <label>Virtual Account UPI</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/recordTypes/Plot.recordType-meta.xml
<RecordType>
    <fullName>Plot</fullName>
    <active>true</active>
    <label>Plot</label>
</RecordType>

force-app/main/default/classes/InstaCollectBatch.cls
/*
*********************************************************
Apex Class Name    : InstaCollectBatch
Created Date       : 18th March 2025
@description       : This class is used to create virtual account details by processing Opportunity and Unit__c records.
It implements the Database.Batchable interface to handle bulk processing and allows callouts.
@author            : Harshit Kumar Rai
Modification Log:
Ver   Date         Author               Modification
1.0   [18th March 2025] Harshit Kumar Rai   Initial Version
*********************************************************
*/
global class InstaCollectBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {
    
    private List<Opportunity> oppList;
    private Set<Id> plotIds;
    
    /*
*********************************************************
@Method Name    : InstaCollectBatch
@author         : Harshit Kumar Rai
@description    : Constructor to initialize the batch class with a list of Opportunities and a set of Unit__c Ids.
@param          : opp - List of Opportunity records to process.
@param          : listOfPlotIds - Set of Plot Ids to process.
*********************************************************
*/
    public InstaCollectBatch(List<Opportunity> opp, Set<Id> listOfPlotIds) {
        this.oppList = opp;
        this.plotIds = listOfPlotIds;
    }
    /*
*********************************************************
@Method Name    : start
@author         : Harshit Kumar Rai
@description    : Start method of the batch class. Returns a QueryLocator to fetch Unit__c records based on the provided plotIds.
@param          : BC - Database.BatchableContext object.
@return         : Database.QueryLocator - QueryLocator for Unit__c records.
*********************************************************
*/
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(
            [SELECT Id FROM Unit__c WHERE Id IN :plotIds]
        );
    }
    
    /*
*********************************************************
@Method Name    : execute
@author         : Harshit Kumar Rai
@description    : Execute method of the batch class. Processes each Unit__c record and calls the EasebuzzInstaCollectService 
to create a virtual account.
@param          : BC - Database.BatchableContext object.
@param          : plotRecords - List of Unit__c records to process.
*********************************************************
*/
    global void execute(Database.BatchableContext BC, List<Unit__c> plotRecords) {
        if (plotRecords != null && !plotRecords.isEmpty()) {
            List<String> plotIdList = New List<String>();
            Map<String,String> plotIdToJsonData = New Map<String,String>();
            
            for (Unit__c plot : plotRecords) {
                String res = JSON.serialize(EasebuzzInstaCollectService.createVirtualAccount(plot.Id));
                if(res!='null'){
                    Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(res);
                    String plotId = (String) responseMap.get('plotId');
                    String jsonData = (String) responseMap.get('jsonData');
                    plotIdList.add(plotId);
                    plotIdToJsonData.put(plotId,jsonData);
                }else{
                    
                }
            }
            
            if(!plotIdList.isEmpty() && !plotIdToJsonData.isEmpty()){
                List<Unit__c> plotList = [
                    SELECT Id, Name, Phase__r.Name, Virtual_Account_Name__c, Virtual_Account_Number__c,
                    Virtual_Account_Id__c, Virtual_Account_UPI__c, Virtual_Account_IFSC__c,
                    UPI_QR_Image__c, UPI_QR_PDF__c, Unique_Request_Number__c
                    FROM Unit__c 
                    WHERE Id IN :plotIdList
                ];
                
                List<Unit__c> plotListToUpdate = new List<Unit__c>();
                for(Unit__c plot :plotList){
                    if(plotIdToJsonData.ContainsKey(plot.Id)){
                        String jsonData = plotIdToJsonData.get(plot.Id);
                        Map<String, Object> data = (Map<String, Object>) JSON.deserializeUntyped(jsonData);
                        if (plot?.Phase__r?.Name != null) {
                            plot.Virtual_Account_Name__c = plot.Name + ' ' + plot?.Phase__r?.Name;
                        }
                        plot.Virtual_Account_Number__c = (String) data.get('virtual_account_number');
                        plot.Virtual_Account_Id__c = (String) data.get('id');
                        plot.Virtual_Account_UPI__c = (String) data.get('virtual_upi_handle');
                        plot.Virtual_Account_IFSC__c = (String) data.get('virtual_ifsc_number');
                        plot.UPI_QR_Image__c = (String) data.get('upi_qrcode_remote_file_location');
                        plot.UPI_QR_PDF__c = (String) data.get('upi_qrcode_scanner_remote_file_location');
                        plot.Unique_Request_Number__c = (String) data.get('unique_request_number');
                        plotListToUpdate.add(plot);
                    }
                    
                }
                if(plotListToUpdate!=null && !plotListToUpdate.isEmpty()){
                    update plotListToUpdate;
                }
            }
        }
    }
    
    /*
*********************************************************
@Method Name    : finish
@author         : Harshit Kumar Rai
@description    : Finish method of the batch class. Executes the next batch (PaymentSendLinkEasyCollect) with the provided Opportunity list.
@param          : BC - Database.BatchableContext object.
*********************************************************
*/
    global void finish(Database.BatchableContext BC) {
        Database.executeBatch(new PaymentSendLinkEasyCollect(oppList), 50);
    }
    
    /*
*********************************************************
Apex Class Name    : ResponseWrapper
@description       : Inner class to wrap response details for API calls or Lightning components.
@author            : Harshit Kumar Rai
*********************************************************
*/
    public class ResponseWrapper {
        @AuraEnabled
        public Boolean isSuccess;
        @AuraEnabled
        public String error;
        @AuraEnabled
        public String response;
        public String integrationLogs;
    }
    
}