force-app/main/default/objects/Opportunity/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <label>Phase</label>
    <nameField>
        <label>Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Phot Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Virtual_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Account_Id__c</fullName>
    <label>Virtual Account Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/recordTypes/Plot.recordType-meta.xml
<RecordType>
    <fullName>Plot</fullName>
    <active>true</active>
    <label>Plot</label>
</RecordType>

force-app/main/default/classes/OpportunityTriggerHandler.cls
public class OpportunityTriggerHandler {
    
	public static void handleAfterInsert(List<Opportunity> newOpportunities) {
        try{
            List<String> opportunityIds = new List<String>();
            for (Opportunity opp : newOpportunities) {
                opportunityIds.add(opp.Id);
            }
            List<Opportunity> oppList = [Select Id, Unit__c, Unit__r.Name, Unit__r.Virtual_Account_Id__c, Unit__r.Phase__c
                                         From Opportunity Where ID IN: opportunityIds];
            
            if(oppList!=null){
                for (Opportunity opp : oppList) {
                    if(opp.Unit__c!=null){
                        if(opp?.Unit__r?.Virtual_Account_Id__c == null){
                        	EasebuzzInstaCollectService.createVirtualAccount(opp.Unit__c);
                        }else{
                            System.Debug('Virtual Account Details Already Present');
                        }
                    }else{
                        System.Debug('Plot is not present');
                    }
                }
            }
            
        }catch (Exception ex){
            throw New AuraHandledException(ex.getMessage());
        }
    }
}