force-app/main/default/objects/Contact/fields/Aadhaar_Card__c.field-meta.xml
<CustomField>
    <fullName>Aadhaar_Card__c</fullName>
    <label>Aadhaar Card</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sale_Value_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sale_Value_Amount__c</fullName>
    <label>Sale Value Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User/fields/Aadhaar_Card__c.field-meta.xml
<CustomField>
    <fullName>Aadhaar_Card__c</fullName>
    <label>Aadhaar Card</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IdbiJuSbiAosControllerTest.cls
@isTest
private class IdbiJuSbiAosControllerTest {
    @testSetup
    static void setupTestData() {
        // Create an Account
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;
        
        // Create a Contact
        Contact testContact = new Contact(FirstName = 'Test', LastName = 'User',
                                          AccountId = testAccount.Id,
                                          Aadhaar_Card__c = '123456781234',
                                          Date_Of_Birth__c = Date.newInstance(1990, 1, 1));
        insert testContact;
        
        // Create an Opportunity
        Opportunity testOpportunity = new Opportunity(Name = 'Test Opportunity',
                                                      StageName = 'Prospecting',
                                                      CloseDate = Date.today().addMonths(1),
                                                      AccountId = testAccount.Id,
                                                      Contact__c = testContact.id,
                                                      Sale_Value_Amount__c = 100000);
        insert testOpportunity;
        
        // Create an OpportunityContactRole
        OpportunityContactRole oppContactRole = new OpportunityContactRole(OpportunityId = testOpportunity.Id, ContactId = testContact.Id, Role = 'Decision Maker');
        insert oppContactRole;
        
        // Create a Payment record
        Payment__c testPayment = new Payment__c(Opportunity__c = testOpportunity.Id,
                                                 Payment_Amount__c = 25000,
                                                 Approval_Status__c = 'Approved',
                                                 Payment_Created_Date__c = Date.today());
        insert testPayment;
    }
    
    @isTest
    static void testControllerInitialization() {
        Test.startTest();
        // Mock page reference
        PageReference pageRef = new PageReference('/apex/IdbiJuSbiAosPage');
        pageRef.getParameters().put('Id', [SELECT Id FROM Opportunity LIMIT 1].Id);
        Test.setCurrentPage(pageRef);
        
        // Instantiate controller
        ApexPages.StandardController stdController = new ApexPages.StandardController([SELECT Id FROM Opportunity LIMIT 1]);
        IdbiJuSbiAosController controller = new IdbiJuSbiAosController(stdController);
        Test.stopTest();
        
        // Assertions
       }
    
    @isTest
    static void testMaskAadhaarNumber() {
        IdbiJuSbiAosController controller = new IdbiJuSbiAosController(new ApexPages.StandardController(new Opportunity()));
        String maskedAadhaar = controller.maskAadhaarNumber('123456781234');
              controller.convertPlotSizeToSqM(10.8);

    }
    
    @isTest
    static void testCalculateAge() {
        IdbiJuSbiAosController controller = new IdbiJuSbiAosController(new ApexPages.StandardController(new Opportunity()));
        Integer age = controller.calculateAge(Date.newInstance(2000, 1, 1));
    }
}