force-app/main/default/objects/BatchClassTime__mdt/BatchClassTime__mdt.object-meta.xml
<CustomObject>
    <label>BatchClassTime</label>
    <pluralLabel>BatchClassTimes</pluralLabel>
</CustomObject>

force-app/main/default/objects/BatchClassTime__mdt/fields/Time_In_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Time_In_Minutes__c</fullName>
    <label>Time In Minutes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0000000000}</displayFormat>
        <label>Integration Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payer Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <label>Payer Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Is_Webhook__c.field-meta.xml
<CustomField>
    <fullName>Is_Webhook__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Webhook</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Merchant_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Transaction_Id__c</fullName>
    <label>Merchant Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Easepay_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Easepay_Id__c</fullName>
    <label>Payment Easepay Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Expiry_Date__c</fullName>
    <label>Payment Expiry Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Gateway__c.field-meta.xml
<CustomField>
    <fullName>Payment_Gateway__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Sent</label>
    <referenceTo>Payment_Gateway__c</referenceTo>
    <relationshipLabel>Payments Received</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>active</fullName>
            </value>
            <value>
                <fullName>success</fullName>
            </value>
            <value>
                <fullName>failure</fullName>
            </value>
            <value>
                <fullName>userCancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EasyCollect</fullName>
            </value>
            <value>
                <fullName>InstaCollect</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Bank (Cheque/Neft)</fullName>
                <isActive>false</isActive>
                <label>Bank (Cheque/Neft)</label>
            </value>
            <value>
                <fullName>Online</fullName>
                <isActive>false</isActive>
                <label>Online</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_URL__c.field-meta.xml
<CustomField>
    <fullName>Payment_URL__c</fullName>
    <label>Payment URL</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Percent_Of_Amount_To_Refund__c.field-meta.xml
<CustomField>
    <fullName>Percent_Of_Amount_To_Refund__c</fullName>
    <label>Percent Of Amount To Refund</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Payer Phone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Gateway__c/Payment_Gateway__c.object-meta.xml
<CustomObject>
    <label>Payment Gateway</label>
    <nameField>
        <displayFormat>PS-{000000000}</displayFormat>
        <label>Payment Gateway Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Gateway__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payer Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Gateways</relationshipLabel>
    <relationshipName>Payment_Gateways</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Gateway__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <label>Payer Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Gateway__c/fields/Merchant_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Transaction_Id__c</fullName>
    <label>Merchant Transaction Id</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Gateway__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payment Gateways</relationshipLabel>
    <relationshipName>Payment_Gateways</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Gateway__c/fields/Payment_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Created_Date__c</fullName>
    <label>Payment Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Payment_Gateway__c/fields/Payment_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Expiry_Date__c</fullName>
    <label>Payment Expiry Date</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Gateway__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>UserCancelled</fullName>
            </value>
            <value>
                <fullName>Initiated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Gateway__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment_Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EasyCollect</fullName>
            </value>
            <value>
                <fullName>InstaCollect</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Gateway__c/fields/Payment_Updated_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Updated_Date__c</fullName>
    <label>Payment Updated Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Payment_Gateway__c/fields/Payment_URL__c.field-meta.xml
<CustomField>
    <fullName>Payment_URL__c</fullName>
    <label>Payment URL</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Payment_Gateway__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Payer Phone</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PaymentTransactionBatch.cls
/**
* Author: Harshit Kumar Rai
* Description: For Payment Transaction Get Status Batch
*/
global class PaymentTransactionBatch implements Database.Batchable<sObject>, Schedulable, Database.AllowsCallouts, Database.Stateful {
    private Decimal timeForRun = 2;
    global Database.QueryLocator start(Database.BatchableContext BC) {
        List<BatchClassTime__mdt> batchTime = [SELECT DeveloperName, Time_In_Minutes__c
                                               FROM BatchClassTime__mdt 
                                               WHERE DeveloperName = 'testBatchClassTime' LIMIT 1];
        if (!batchTime.isEmpty()) {
            BatchClassTime__mdt batch = batchTime[0];
            timeForRun = batch.Time_In_Minutes__c;
        }
        
        DateTime currentDateTime = System.Now();
        return Database.getQueryLocator([
            SELECT Id, Merchant_Transaction_Id__c, Email_Address__c, Phone__c, Payment_Amount__c, 
            			Payment_Status__c, Opportunity__c, Payment_Type__c, Contact_Name__c,
						Payment_URL__c, Payment_Id__c, Payment_Expiry_Date__c, Payment_Updated_Date__c,
						Payment_Created_Date__c
            			FROM Payment_Gateway__c 
            			WHERE Merchant_Transaction_Id__c != null AND Email_Address__c!=null AND 
            			Phone__c!=null AND Payment_Amount__c!=null AND Payment_Status__c!='Success'
						AND Payment_Status__c!='UserCancelled' AND Payment_Expiry_Date__c>=:currentDateTime
        ]);
    }

    global void execute(Database.BatchableContext BC, List<Payment_Gateway__c> paymentRecords) {
        Map<String, Payment_Gateway__c> paymentMap = new Map<String, Payment_Gateway__c>();
        for (Payment_Gateway__c payment : paymentRecords) {
            paymentMap.put(payment.Merchant_Transaction_Id__c, payment);
        }
        List<String> merchantIdList = New List<String>();
        List<Payment__c> updatedPayments = new List<Payment__c>();
        List<Payment_Gateway__c> paymentGateWayToUpdate = new List<Payment_Gateway__c>();
        List<Integration_Log__c> integrationLogs = new List<Integration_Log__c>();
        
        for (String txnId : paymentMap.keySet()) {
            Payment_Gateway__c paymentRecord = paymentMap.get(txnId);
            String apiResponse = EasyCollectPayment.getTransactionDetails(paymentRecord.Merchant_Transaction_Id__c, paymentRecord.Payment_Amount__c, paymentRecord.Email_Address__c,paymentRecord.Phone__c);
            Map<String, Object> responseWrapper = (Map<String, Object>) JSON.deserializeUntyped(apiResponse);
            Boolean isSuccess = (Boolean) responseWrapper.get('isSuccess');
            String errorWrapper = (String) responseWrapper.get('error');
            String response = (String) responseWrapper.get('response');
            String integrationLogsStr = (String) responseWrapper.get('integrationLogs');
            if (isSuccess && String.isNotBlank(response)) {
                try {
                    Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(response);
                    Boolean statusOfResponse = (Boolean) responseMap.get('status');
                    Payment__c payment = new Payment__c();
                    payment.Payment_Amount__c = paymentRecord.Payment_Amount__c;
                    payment.Email_Address__c = paymentRecord.Email_Address__c;
                    payment.Merchant_Transaction_Id__c = paymentRecord.Merchant_Transaction_Id__c;
                    payment.Opportunity__c = paymentRecord.Opportunity__c;
                    payment.Payment_Created_Date__c = paymentRecord.Payment_Created_Date__c;
                    // To Be Checked Updated Date
                    payment.Payment_Updated_Date__c = System.now();
                    payment.Payment_Expiry_Date__c = paymentRecord.Payment_Expiry_Date__c;
                    payment.Payment_Id__c = paymentRecord.Payment_Id__c;
                    payment.Payment_Status__c = paymentRecord.Payment_Status__c;
                    payment.Payment_URL__c = paymentRecord.Payment_URL__c;
                    payment.Contact_Name__c = paymentRecord.Contact_Name__c;
                    payment.Payment_Type__c = paymentRecord.Payment_Type__c;
                    payment.Phone__c=paymentRecord.Phone__c;
                    payment.Payment_Gateway__c = paymentRecord.Id;
                    payment.Percent_Of_Amount_To_Refund__c=100;
                    if (statusOfResponse && responseMap.containsKey('msg')) {
                        Map<String, Object> transactionData = (Map<String, Object>) responseMap.get('msg');
                        String mode = (String) transactionData.get('mode');
                        String status = (String) transactionData.get('status');
                        String error = (String) transactionData.get('error');
                        String easepayId = (String) transactionData.get('easepayid');
                        String errorMessage = (String) transactionData.get('error_Message');
                        payment.Payment_Status__c = status;
                        payment.Payment_Mode__c = mode;
                        payment.Payment_Easepay_Id__c = easepayId;
                        payment.Is_Webhook__c = true;
                        payment.Error_Message__c = errorMessage;
                        paymentRecord.Payment_Status__c=status;
                        updatedPayments.add(payment);
                        paymentGateWayToUpdate.add(paymentRecord);
                        Integration_Log__c log = null;
                        if (String.isNotBlank(integrationLogsStr)) {
                            log = (Integration_Log__c) JSON.deserialize(integrationLogsStr, Integration_Log__c.class);
                            //integrationLogs.add(log);
                        }
                    }else{
                        String message= (String) responseMap.get('msg');
                        payment.Error_Message__c = message;
                        updatedPayments.add(payment);
                        Integration_Log__c log = null;
                        if (String.isNotBlank(integrationLogsStr)) {
                            log = (Integration_Log__c) JSON.deserialize(integrationLogsStr, Integration_Log__c.class);
                            integrationLogs.add(log);
                        }
                    }
                    merchantIdList.add(paymentRecord.Merchant_Transaction_Id__c);
                } catch (Exception e) {
                    System.debug('Error parsing response: ' + e.getMessage());
                }
            }else if(!isSuccess){
                Integration_Log__c log = null;
                if (String.isNotBlank(integrationLogsStr)) {
                	log = (Integration_Log__c) JSON.deserialize(integrationLogsStr, Integration_Log__c.class);
                    integrationLogs.add(log);
                }
            }else{
                Integration_Log__c log = null;
                if (String.isNotBlank(integrationLogsStr)) {
                	log = (Integration_Log__c) JSON.deserialize(integrationLogsStr, Integration_Log__c.class);
                    integrationLogs.add(log);
                }
            }
        }
		if (!integrationLogs.isEmpty()) {
            // insert integrationLogs;
        }
        if (!updatedPayments.isEmpty()) {
            List<Payment__c> updatedPaymentList = New List<Payment__c>();
            List<Payment__c> paymentList = [Select Id,Merchant_Transaction_Id__c From Payment__c 
                                            Where Merchant_Transaction_Id__c IN: merchantIdList];
            Map<String, String> merchantIdMap = new Map<String, String>();
            for(Payment__c payment:paymentList){
                merchantIdMap.put(payment.Merchant_Transaction_Id__c,payment.Id);
            }
            for(Payment__c payment:updatedPayments){
                if(merchantIdMap.ContainsKey(payment.Merchant_Transaction_Id__c)){
                    payment.Id=merchantIdMap.get(payment.Merchant_Transaction_Id__c);
                }
                updatedPaymentList.add(payment);
            }
            if (!updatedPaymentList.isEmpty()) {
                upsert updatedPaymentList;
            }
        }
        if (!paymentGateWayToUpdate.isEmpty()) {
            update paymentGateWayToUpdate;
        }
    }

    global void finish(Database.BatchableContext BC) {
        DateTime nextRun = System.now().addMinutes(Integer.ValueOf(timeForRun));
        String cronExp = nextRun.second() + ' ' +
                         nextRun.minute() + ' ' +
                         nextRun.hour() + ' ' +
                         nextRun.day() + ' ' +
                         nextRun.month() + ' ? ' +
                         nextRun.year();
        System.schedule('PaymentTransactionBatch '+ String.valueOf(Datetime.now()), cronExp, new PaymentTransactionBatch());
    }

    global void execute(SchedulableContext sc) {
        Database.executeBatch(new PaymentTransactionBatch(), 10);
        System.abortJob(sc.getTriggerId());
    }
}