force-app/main/default/objects/BatchClassTime__mdt/BatchClassTime__mdt.object-meta.xml
<CustomObject>
    <label>BatchClassTime</label>
    <pluralLabel>BatchClassTimes</pluralLabel>
</CustomObject>

force-app/main/default/objects/BatchClassTime__mdt/fields/Time_In_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Time_In_Minutes__c</fullName>
    <label>Time In Minutes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0000000000}</displayFormat>
        <label>Integration Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <formula>Contact__r.Email</formula>
    <label>Contact Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Mode__c.field-meta.xml
<CustomField>
    <fullName>Payment_Mode__c</fullName>
    <label>Payment Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>NEFT</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>UPI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Default.recordType-meta.xml
<RecordType>
    <fullName>Default</fullName>
    <active>true</active>
    <businessProcess>Sale Process</businessProcess>
    <label>Default</label>
</RecordType>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <label>Payer Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/InstaCollect_Bank_Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>InstaCollect_Bank_Settlement_Date__c</fullName>
    <label>InstaCollect Bank Settlement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/InstaCollect_Narration__c.field-meta.xml
<CustomField>
    <fullName>InstaCollect_Narration__c</fullName>
    <label>InstaCollect Narration</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/InstaCollect_Settled_By_Bank__c.field-meta.xml
<CustomField>
    <fullName>InstaCollect_Settled_By_Bank__c</fullName>
    <defaultValue>false</defaultValue>
    <label>InstaCollect Settled By Bank</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/InstaCollect_Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>InstaCollect_Settlement_Date__c</fullName>
    <label>InstaCollect Settlement Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/InstaCollect_Status__c.field-meta.xml
<CustomField>
    <fullName>InstaCollect_Status__c</fullName>
    <label>InstaCollect Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/InstaCollect_Transaction_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>InstaCollect_Transaction_Date_Time__c</fullName>
    <label>InstaCollect Transaction Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/InstaCollect_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>InstaCollect_Transaction_Id__c</fullName>
    <label>InstaCollect Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/InstaCollect_Transaction_Reference__c.field-meta.xml
<CustomField>
    <fullName>InstaCollect_Transaction_Reference__c</fullName>
    <label>InstaCollect Transaction Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EasyCollect</fullName>
            </value>
            <value>
                <fullName>InstaCollect</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Bank (Cheque/Neft)</fullName>
                <isActive>false</isActive>
                <label>Bank (Cheque/Neft)</label>
            </value>
            <value>
                <fullName>Online</fullName>
                <isActive>false</isActive>
                <label>Online</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Percent_Of_Amount_To_Refund__c.field-meta.xml
<CustomField>
    <fullName>Percent_Of_Amount_To_Refund__c</fullName>
    <label>Percent Of Amount To Refund</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Remitter_Account_IFSC__c.field-meta.xml
<CustomField>
    <fullName>Remitter_Account_IFSC__c</fullName>
    <label>Remitter Account IFSC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Remitter_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Remitter_Account_Number__c</fullName>
    <label>Remitter Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Remitter_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Remitter_Full_Name__c</fullName>
    <label>Remitter Full Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Remitter_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Remitter_Phone_Number__c</fullName>
    <label>Remitter Phone Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Remitter_UPI_Handle__c.field-meta.xml
<CustomField>
    <fullName>Remitter_UPI_Handle__c</fullName>
    <label>Remitter UPI Handle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Phot Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Management Blocked</fullName>
            </value>
            <value>
                <fullName>Mortgage</fullName>
            </value>
            <value>
                <fullName>Not For Sale</fullName>
            </value>
            <value>
                <fullName>Temp Blocked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Virtual_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Account_Id__c</fullName>
    <label>Virtual Account Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PaymentTransactionInstaCollectBatch.cls
/*
*********************************************************
Apex Class Name    : PaymentTransactionInstaCollectBatch
Created Date       : [Insert Date]
@description       : This batch class is responsible for fetching and updating the status of InstaCollect payment 
                     transactions by making callouts to the Easebuzz InstaCollect API. It processes opportunities 
                     linked to units with virtual accounts and updates payment records with transaction details. 
                     The class implements Database.Batchable, Schedulable, and allows callouts.
@author            : Harshit Kumar Rai
Modification Log:
Ver   Date         Author                               Modification
1.0   [Insert Date] Harshit Kumar Rai                   Initial Version
*********************************************************
*/
global class PaymentTransactionInstaCollectBatch implements Database.Batchable<sObject>, Schedulable, Database.AllowsCallouts, Database.Stateful {
    private Decimal timeForRun = 2; // Default time interval for scheduling the next batch run

    /*
    *********************************************************
    @Method Name    : start
    @author         : Harshit Kumar Rai
    @description    : This method is the starting point of the batch process. It queries the custom metadata 
                       to determine the time interval for the next batch run and returns a QueryLocator for 
                       opportunities linked to units with virtual accounts.
    @param          : Database.BatchableContext BC - The context of the batch job.
    @return         : Database.QueryLocator - A query locator for opportunities to process.
    ********************************************************
    */
    global Database.QueryLocator start(Database.BatchableContext BC) {
        // Fetch the time interval for the next batch run from custom metadata
        List<BatchClassTime__mdt> batchTime = [SELECT DeveloperName, Time_In_Minutes__c
                                               FROM BatchClassTime__mdt 
                                               WHERE DeveloperName = 'testBatchClassTime' LIMIT 1];
        if (!batchTime.isEmpty()) {
            BatchClassTime__mdt batch = batchTime[0];
            timeForRun = batch.Time_In_Minutes__c;
        }
        
        // Query opportunities linked to units with virtual accounts
        return Database.getQueryLocator([
            // More Filter Conditions Are Required For Optimization
            SELECT Id, Unit__c, Unit__r.Virtual_Account_Id__c,Contact_Email__c
            FROM Opportunity 
            WHERE Unit__c != null AND Unit__r.Virtual_Account_Id__c != null 
            AND Unit__r.Virtual_Account_Id__c != '' AND Unit__r.Status__c != 'Available'
            AND Unit__r.Status__c != 'Sold'
        ]);
    }

    /*
    *********************************************************
    @Method Name    : execute
    @author         : Harshit Kumar Rai
    @description    : This method processes a batch of opportunities, makes callouts to the Easebuzz InstaCollect API 
                       to fetch transaction details, and updates payment records and integration logs accordingly.
    @param          : Database.BatchableContext BC - The context of the batch job.
    @param          : List<Opportunity> oppRecords - The list of opportunities to process.
    ********************************************************
    */
    global void execute(Database.BatchableContext BC, List<Opportunity> oppRecords) {
        List<String> virtualAccountIdList = new List<String>();
        List<Payment__c> updatedPayments = new List<Payment__c>();
        List<Integration_Log__c> integrationLogs = new List<Integration_Log__c>();
        
        for (Opportunity opp : oppRecords) {
            // Call the Easebuzz InstaCollect API to fetch transaction details
            String apiResponse = EasebuzzInstaCollectService.retrieveTransactionsList(opp.Unit__r.Virtual_Account_Id__c);
            Map<String, Object> responseWrapper = (Map<String, Object>) JSON.deserializeUntyped(apiResponse);
            Boolean isSuccess = (Boolean) responseWrapper.get('isSuccess');
            String errorWrapper = (String) responseWrapper.get('error');
            String response = (String) responseWrapper.get('response');
            String integrationLogsStr = (String) responseWrapper.get('integrationLogs');
            
            if (isSuccess && String.isNotBlank(response)) {
                try {
                    Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(response);
                    Map<String, Object> data = (Map<String, Object>) responseMap.get('data');
                    
                    if (data.containsKey('results')) {
                        List<Object> results = (List<Object>) data.get('results');
                        for (Object resultObj : results) {
                            Map<String, Object> transactions = (Map<String, Object>) resultObj;
                            
                            // Extract transaction details
                            String id = (String) transactions.get('id');
                            String status1 = (String) transactions.get('status');
                            String createdDate = (String) transactions.get('created_at');
                            String paymentMode = (String) transactions.get('payment_mode');
                            Decimal amount = (Decimal) transactions.get('amount');
                            String transactionDateTime = (String) transactions.get('transaction_date');
                            String uniqueTransactionReference = (String) transactions.get('unique_transaction_reference');
                            String remitterAccountNumber = (String) transactions.get('remitter_account_number');
                            String remitterAccountIfsc = (String) transactions.get('remitter_account_ifsc');
                            String remitterUpiHandle = (String) transactions.get('remitter_upi_handle');
                            String remitterFullName = (String) transactions.get('remitter_full_name');
                            String remitterPhoneNumber = (String) transactions.get('remitter_phone_number');
                            String settlementDate = (String) transactions.get('settlement_date');
                            Boolean is_settled_by_bank = (Boolean) transactions.get('is_settled_by_bank');
                            String bankSettlementDate = (String) transactions.get('bank_settlement_date');
                            String narration = (String) transactions.get('narration');
                            
                            String virtualAccountNumber = null;
                            if (transactions.containsKey('virtual_account')) {
                                Map<String, Object> virtualAccount = (Map<String, Object>) transactions.get('virtual_account');
                                virtualAccountNumber = (String) virtualAccount.get('virtual_account_number');
                            }
                            
                            // Create or update payment record with transaction details
                            Payment__c payment = new Payment__c();
                            payment.InstaCollect_Transaction_Id__c = id;
                            if (status1 != null) {
                                payment.InstaCollect_Status__c = status1.substring(0, 1).toUpperCase() + status1.substring(1);
                            }
                            if (createdDate != null) {
                                payment.Payment_Created_Date__c = Datetime.valueOf(createdDate.substring(0, 19).replace('T', ' '));
                            }
                            payment.Payment_Updated_Date__c = System.now();
                            payment.Payment_Mode__c = paymentMode;
                            payment.Payment_Amount__c = amount;
                            if (transactionDateTime != null) {
                                payment.InstaCollect_Transaction_Date_Time__c = Datetime.valueOf(transactionDateTime.substring(0, 19).replace('T', ' '));
                            }
                            payment.Opportunity__c = opp.Id;
                            payment.InstaCollect_Transaction_Reference__c = uniqueTransactionReference;
                            payment.Remitter_Account_Number__c = remitterAccountNumber;
                            payment.Remitter_Account_IFSC__c = remitterAccountIfsc;
                            payment.Remitter_UPI_Handle__c = remitterUpiHandle;
                            payment.Remitter_Full_Name__c = remitterFullName;
                            payment.Remitter_Phone_Number__c = remitterPhoneNumber;
                            if (bankSettlementDate != null) {
                                payment.InstaCollect_Bank_Settlement_Date__c = Date.valueOf(bankSettlementDate);
                            }
                            if (settlementDate != null) {
                                payment.InstaCollect_Settlement_Date__c = Datetime.valueOf(settlementDate.substring(0, 19).replace('T', ' '));
                            }
                            payment.InstaCollect_Settled_By_Bank__c = is_settled_by_bank;
                            payment.InstaCollect_Narration__c = narration;
                            payment.Payment_Type__c = 'InstaCollect';
                            payment.Percent_Of_Amount_To_Refund__c = 100;
                            payment.Email_Address__c=opp.Contact_Email__c;
                            updatedPayments.add(payment);
                            virtualAccountIdList.add(id);
                            
                            // Log integration details if available
                            Integration_Log__c log = null;
                            if (String.isNotBlank(integrationLogsStr)) {
                                log = (Integration_Log__c) JSON.deserialize(integrationLogsStr, Integration_Log__c.class);
                                integrationLogs.add(log);
                            }
                        }
                    }
                } catch (Exception e) {
                    System.debug('Error parsing response: ' + e.getMessage());
                }
            } else {
                // Log integration details if the API call is unsuccessful
                Integration_Log__c log = null;
                if (String.isNotBlank(integrationLogsStr)) {
                    log = (Integration_Log__c) JSON.deserialize(integrationLogsStr, Integration_Log__c.class);
                    integrationLogs.add(log);
                }
            }
        }
        
        // Insert integration logs and update payment records
        if (!integrationLogs.isEmpty()) {
            // insert integrationLogs; // Uncomment if logs need to be inserted
        }
        if (!updatedPayments.isEmpty()) {
            List<Payment__c> updatedPaymentList = new List<Payment__c>();
            List<Payment__c> paymentList = [SELECT Id, InstaCollect_Transaction_Id__c FROM Payment__c 
                                            WHERE InstaCollect_Transaction_Id__c IN :virtualAccountIdList];
            Map<String, String> transactionIdMap = new Map<String, String>();
            Map<String, String> idToEmailMap = new Map<String, String>();
            for (Payment__c payment : paymentList) {
                transactionIdMap.put(payment.InstaCollect_Transaction_Id__c, payment.Id);
            }
            for (Payment__c payment : updatedPayments) {
                if (transactionIdMap.containsKey(payment.InstaCollect_Transaction_Id__c)) {
                    payment.Id = transactionIdMap.get(payment.InstaCollect_Transaction_Id__c);
                }
                updatedPaymentList.add(payment);
            }
            if (!updatedPaymentList.isEmpty()) {
                upsert updatedPaymentList;
                List<Id> recordIds = new List<Id>();
                for (Payment__c p : updatedPaymentList) {
                    if (p.InstaCollect_Status__c == 'Received') {
                        recordIds.add(p.Id);
                        idToEmailMap.put(p.Id, p.Email_Address__c);
                    }
                }
                if (!recordIds.isEmpty()) {
                    List<Payment__c> pList = [Select Id,Opportunity__r.OwnerId From Payment__c Where Id IN:recordIds];
                    Map<String,String> paymentIdToOppOwnerId = New Map<String,String>();
                    if(pList!=null){
                        for(Payment__c p:pList){
                            paymentIdToOppOwnerId.put(p.Id,p.Opportunity__r.OwnerId);
                        }
                    }
                    submitForApproval(recordIds,paymentIdToOppOwnerId);
                    if(!idToEmailMap.isEmpty()){
                        System.enqueueJob(new PaymentReceiptQueueable(idToEmailMap, recordIds));
                    }
                }
            }
        }
    }

    /*
    *********************************************************
    @Method Name    : finish
    @author         : Harshit Kumar Rai
    @description    : This method is called when the batch job finishes. It schedules the next run of the 
                       batch job based on the configured time interval.
    @param          : Database.BatchableContext BC - The context of the batch job.
    ********************************************************
    */
    global void finish(Database.BatchableContext BC) {
        DateTime nextRun = System.now().addMinutes(Integer.ValueOf(timeForRun));
        String cronExp = nextRun.second() + ' ' +
                         nextRun.minute() + ' ' +
                         nextRun.hour() + ' ' +
                         nextRun.day() + ' ' +
                         nextRun.month() + ' ? ' +
                         nextRun.year();
        System.schedule('PaymentTransactionInstaCollect ' + String.valueOf(Datetime.now()), cronExp, new PaymentTransactionInstaCollectBatch());
    }

    /*
    *********************************************************
    @Method Name    : execute (Schedulable)
    @author         : Harshit Kumar Rai
    @description    : This method is called when the class is executed as a scheduled job. It starts the 
                       batch process and aborts the current scheduled job.
    @param          : SchedulableContext sc - The context of the scheduled job.
    ********************************************************
    */
    global void execute(SchedulableContext sc) {
        Database.executeBatch(new PaymentTransactionInstaCollectBatch(), 10);
        System.abortJob(sc.getTriggerId());
    }

    /*
    *********************************************************
    @Method Name    : submitForApproval
    @author         : Harshit Kumar Rai
    @description    : This method submits payment records for approval if their status is 'Received'.
    @param          : List<Id> recordIds - The list of payment record IDs to submit for approval.
    ********************************************************
    */
    public static void submitForApproval(List<Id> recordIds, Map<String,String> paymentIdToOppOwnerId) {
        try {
            List<Approval.ProcessSubmitRequest> submitRequests = new List<Approval.ProcessSubmitRequest>();
            
            for (Id recordId : recordIds) {
                String userId='';
                if(paymentIdToOppOwnerId.ContainsKey(recordId)){
                    userId=paymentIdToOppOwnerId.get(recordId);
                }
                Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
                req.setObjectId(recordId);
                req.setComments('Approval Request For Payment');
                req.setNextApproverIds(null);
                req.setProcessDefinitionNameOrId('Payment_Approval_Process');
                if(userId!=''){
                    req.setSubmitterId(userId);
                }
                submitRequests.add(req);
            }
            
            // Submit all requests in bulk
            List<Approval.ProcessResult> results = Approval.process(submitRequests);
            
            // Validate that each approval submission was successful
            for (Approval.ProcessResult result : results) {
                if (!result.isSuccess()) {
                    System.debug('Approval process failed for one or more records.');
                }
            }
        } catch (Exception ex) {
            System.debug('Error triggering approval process: ' + ex.getMessage());
        }
    }
}